# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v7/resources/campaign_criterion_simulation.proto

require 'google/protobuf'

require 'google/ads/google_ads/v7/common/simulation_pb'
require 'google/ads/google_ads/v7/enums/simulation_modification_method_pb'
require 'google/ads/google_ads/v7/enums/simulation_type_pb'
require 'google/api/field_behavior_pb'
require 'google/api/resource_pb'
require 'google/api/annotations_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/ads/googleads/v7/resources/campaign_criterion_simulation.proto", :syntax => :proto3) do
    add_message "google.ads.googleads.v7.resources.CampaignCriterionSimulation" do
      optional :resource_name, :string, 1
      proto3_optional :campaign_id, :int64, 9
      proto3_optional :criterion_id, :int64, 10
      optional :type, :enum, 4, "google.ads.googleads.v7.enums.SimulationTypeEnum.SimulationType"
      optional :modification_method, :enum, 5, "google.ads.googleads.v7.enums.SimulationModificationMethodEnum.SimulationModificationMethod"
      proto3_optional :start_date, :string, 11
      proto3_optional :end_date, :string, 12
      oneof :point_list do
        optional :bid_modifier_point_list, :message, 8, "google.ads.googleads.v7.common.BidModifierSimulationPointList"
      end
    end
  end
end

module Google
  module Ads
    module GoogleAds
      module V7
        module Resources
          CampaignCriterionSimulation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v7.resources.CampaignCriterionSimulation").msgclass
        end
      end
    end
  end
end
