# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v21/enums/interaction_event_type.proto

require 'google/protobuf'


descriptor_data = "\n;google/ads/googleads/v21/enums/interaction_event_type.proto\x12\x1egoogle.ads.googleads.v21.enums\"\x85\x01\n\x18InteractionEventTypeEnum\"i\n\x14InteractionEventType\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x0b\n\x07UNKNOWN\x10\x01\x12\t\n\x05\x43LICK\x10\x02\x12\x0e\n\nENGAGEMENT\x10\x03\x12\x0e\n\nVIDEO_VIEW\x10\x04\x12\x08\n\x04NONE\x10\x05\x42\xf3\x01\n\"com.google.ads.googleads.v21.enumsB\x19InteractionEventTypeProtoP\x01ZCgoogle.golang.org/genproto/googleapis/ads/googleads/v21/enums;enums\xa2\x02\x03GAA\xaa\x02\x1eGoogle.Ads.GoogleAds.V21.Enums\xca\x02\x1eGoogle\\Ads\\GoogleAds\\V21\\Enums\xea\x02\"Google::Ads::GoogleAds::V21::Enumsb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Google
  module Ads
    module GoogleAds
      module V21
        module Enums
          InteractionEventTypeEnum = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v21.enums.InteractionEventTypeEnum").msgclass
          InteractionEventTypeEnum::InteractionEventType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v21.enums.InteractionEventTypeEnum.InteractionEventType").enummodule
        end
      end
    end
  end
end
