# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v21/enums/multi_party_auth_review_target_resource.proto

require 'google/protobuf'


descriptor_data = "\nLgoogle/ads/googleads/v21/enums/multi_party_auth_review_target_resource.proto\x12\x1egoogle.ads.googleads.v21.enums\"\xac\x01\n&MultiPartyAuthReviewTargetResourceEnum\"\x81\x01\n\"MultiPartyAuthReviewTargetResource\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x0b\n\x07UNKNOWN\x10\x01\x12\x18\n\x14\x43USTOMER_USER_ACCESS\x10\x02\x12#\n\x1f\x43USTOMER_USER_ACCESS_INVITATION\x10\x03\x42\x81\x02\n\"com.google.ads.googleads.v21.enumsB\'MultiPartyAuthReviewTargetResourceProtoP\x01ZCgoogle.golang.org/genproto/googleapis/ads/googleads/v21/enums;enums\xa2\x02\x03GAA\xaa\x02\x1eGoogle.Ads.GoogleAds.V21.Enums\xca\x02\x1eGoogle\\Ads\\GoogleAds\\V21\\Enums\xea\x02\"Google::Ads::GoogleAds::V21::Enumsb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Google
  module Ads
    module GoogleAds
      module V21
        module Enums
          MultiPartyAuthReviewTargetResourceEnum = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v21.enums.MultiPartyAuthReviewTargetResourceEnum").msgclass
          MultiPartyAuthReviewTargetResourceEnum::MultiPartyAuthReviewTargetResource = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v21.enums.MultiPartyAuthReviewTargetResourceEnum.MultiPartyAuthReviewTargetResource").enummodule
        end
      end
    end
  end
end
