# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v21/enums/product_status.proto

require 'google/protobuf'


descriptor_data = "\n3google/ads/googleads/v21/enums/product_status.proto\x12\x1egoogle.ads.googleads.v21.enums\"x\n\x11ProductStatusEnum\"c\n\rProductStatus\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x0b\n\x07UNKNOWN\x10\x01\x12\x10\n\x0cNOT_ELIGIBLE\x10\x02\x12\x14\n\x10\x45LIGIBLE_LIMITED\x10\x03\x12\x0c\n\x08\x45LIGIBLE\x10\x04\x42\xec\x01\n\"com.google.ads.googleads.v21.enumsB\x12ProductStatusProtoP\x01ZCgoogle.golang.org/genproto/googleapis/ads/googleads/v21/enums;enums\xa2\x02\x03GAA\xaa\x02\x1eGoogle.Ads.GoogleAds.V21.Enums\xca\x02\x1eGoogle\\Ads\\GoogleAds\\V21\\Enums\xea\x02\"Google::Ads::GoogleAds::V21::Enumsb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Google
  module Ads
    module GoogleAds
      module V21
        module Enums
          ProductStatusEnum = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v21.enums.ProductStatusEnum").msgclass
          ProductStatusEnum::ProductStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v21.enums.ProductStatusEnum.ProductStatus").enummodule
        end
      end
    end
  end
end
