# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v8/errors/change_event_error.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/ads/googleads/v8/errors/change_event_error.proto", :syntax => :proto3) do
    add_message "google.ads.googleads.v8.errors.ChangeEventErrorEnum" do
    end
    add_enum "google.ads.googleads.v8.errors.ChangeEventErrorEnum.ChangeEventError" do
      value :UNSPECIFIED, 0
      value :UNKNOWN, 1
      value :START_DATE_TOO_OLD, 2
      value :CHANGE_DATE_RANGE_INFINITE, 3
      value :CHANGE_DATE_RANGE_NEGATIVE, 4
      value :LIMIT_NOT_SPECIFIED, 5
      value :INVALID_LIMIT_CLAUSE, 6
    end
  end
end

module Google
  module Ads
    module GoogleAds
      module V8
        module Errors
          ChangeEventErrorEnum = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v8.errors.ChangeEventErrorEnum").msgclass
          ChangeEventErrorEnum::ChangeEventError = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v8.errors.ChangeEventErrorEnum.ChangeEventError").enummodule
        end
      end
    end
  end
end
