# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v13/enums/asset_set_asset_status.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/ads/googleads/v13/enums/asset_set_asset_status.proto", :syntax => :proto3) do
    add_message "google.ads.googleads.v13.enums.AssetSetAssetStatusEnum" do
    end
    add_enum "google.ads.googleads.v13.enums.AssetSetAssetStatusEnum.AssetSetAssetStatus" do
      value :UNSPECIFIED, 0
      value :UNKNOWN, 1
      value :ENABLED, 2
      value :REMOVED, 3
    end
  end
end

module Google
  module Ads
    module GoogleAds
      module V13
        module Enums
          AssetSetAssetStatusEnum = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v13.enums.AssetSetAssetStatusEnum").msgclass
          AssetSetAssetStatusEnum::AssetSetAssetStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v13.enums.AssetSetAssetStatusEnum.AssetSetAssetStatus").enummodule
        end
      end
    end
  end
end
