# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/google_ads/v3/resources/mobile_app_category_constant.proto

require 'google/protobuf'

require 'google/api/resource_pb'
require 'google/protobuf/wrappers_pb'
require 'google/api/annotations_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "google.ads.googleads.v3.resources.MobileAppCategoryConstant" do
    optional :resource_name, :string, 1
    optional :id, :message, 2, "google.protobuf.Int32Value"
    optional :name, :message, 3, "google.protobuf.StringValue"
  end
end

module Google::Ads::GoogleAds::V3::Resources
  MobileAppCategoryConstant = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v3.resources.MobileAppCategoryConstant").msgclass
end
