# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v9/errors/string_length_error.proto

require 'google/api/annotations_pb'
require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/ads/googleads/v9/errors/string_length_error.proto", :syntax => :proto3) do
    add_message "google.ads.googleads.v9.errors.StringLengthErrorEnum" do
    end
    add_enum "google.ads.googleads.v9.errors.StringLengthErrorEnum.StringLengthError" do
      value :UNSPECIFIED, 0
      value :UNKNOWN, 1
      value :EMPTY, 4
      value :TOO_SHORT, 2
      value :TOO_LONG, 3
    end
  end
end

module Google
  module Ads
    module GoogleAds
      module V9
        module Errors
          StringLengthErrorEnum = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v9.errors.StringLengthErrorEnum").msgclass
          StringLengthErrorEnum::StringLengthError = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v9.errors.StringLengthErrorEnum.StringLengthError").enummodule
        end
      end
    end
  end
end
