# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v23/errors/asset_set_link_error.proto

require 'google/protobuf'


descriptor_data = "\n:google/ads/googleads/v23/errors/asset_set_link_error.proto\x12\x1fgoogle.ads.googleads.v23.errors\"\x87\x02\n\x15\x41ssetSetLinkErrorEnum\"\xed\x01\n\x11\x41ssetSetLinkError\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x0b\n\x07UNKNOWN\x10\x01\x12)\n%INCOMPATIBLE_ADVERTISING_CHANNEL_TYPE\x10\x02\x12\x17\n\x13\x44UPLICATE_FEED_LINK\x10\x03\x12\x32\n.INCOMPATIBLE_ASSET_SET_TYPE_WITH_CAMPAIGN_TYPE\x10\x04\x12\x1c\n\x18\x44UPLICATE_ASSET_SET_LINK\x10\x05\x12$\n ASSET_SET_LINK_CANNOT_BE_REMOVED\x10\x06\x42\xf6\x01\n#com.google.ads.googleads.v23.errorsB\x16\x41ssetSetLinkErrorProtoP\x01ZEgoogle.golang.org/genproto/googleapis/ads/googleads/v23/errors;errors\xa2\x02\x03GAA\xaa\x02\x1fGoogle.Ads.GoogleAds.V23.Errors\xca\x02\x1fGoogle\\Ads\\GoogleAds\\V23\\Errors\xea\x02#Google::Ads::GoogleAds::V23::Errorsb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Google
  module Ads
    module GoogleAds
      module V23
        module Errors
          AssetSetLinkErrorEnum = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v23.errors.AssetSetLinkErrorEnum").msgclass
          AssetSetLinkErrorEnum::AssetSetLinkError = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v23.errors.AssetSetLinkErrorEnum.AssetSetLinkError").enummodule
        end
      end
    end
  end
end
