# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v23/errors/reach_plan_error.proto

require 'google/protobuf'


descriptor_data = "\n6google/ads/googleads/v23/errors/reach_plan_error.proto\x12\x1fgoogle.ads.googleads.v23.errors\"\xbd\x01\n\x12ReachPlanErrorEnum\"\xa6\x01\n\x0eReachPlanError\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x0b\n\x07UNKNOWN\x10\x01\x12!\n\x1dNOT_FORECASTABLE_MISSING_RATE\x10\x02\x12)\n%NOT_FORECASTABLE_NOT_ENOUGH_INVENTORY\x10\x03\x12(\n$NOT_FORECASTABLE_ACCOUNT_NOT_ENABLED\x10\x04\x42\xf3\x01\n#com.google.ads.googleads.v23.errorsB\x13ReachPlanErrorProtoP\x01ZEgoogle.golang.org/genproto/googleapis/ads/googleads/v23/errors;errors\xa2\x02\x03GAA\xaa\x02\x1fGoogle.Ads.GoogleAds.V23.Errors\xca\x02\x1fGoogle\\Ads\\GoogleAds\\V23\\Errors\xea\x02#Google::Ads::GoogleAds::V23::Errorsb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Google
  module Ads
    module GoogleAds
      module V23
        module Errors
          ReachPlanErrorEnum = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v23.errors.ReachPlanErrorEnum").msgclass
          ReachPlanErrorEnum::ReachPlanError = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v23.errors.ReachPlanErrorEnum.ReachPlanError").enummodule
        end
      end
    end
  end
end
