# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v10/enums/ad_group_criterion_status.proto

require 'google/api/annotations_pb'
require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/ads/googleads/v10/enums/ad_group_criterion_status.proto", :syntax => :proto3) do
    add_message "google.ads.googleads.v10.enums.AdGroupCriterionStatusEnum" do
    end
    add_enum "google.ads.googleads.v10.enums.AdGroupCriterionStatusEnum.AdGroupCriterionStatus" do
      value :UNSPECIFIED, 0
      value :UNKNOWN, 1
      value :ENABLED, 2
      value :PAUSED, 3
      value :REMOVED, 4
    end
  end
end

module Google
  module Ads
    module GoogleAds
      module V10
        module Enums
          AdGroupCriterionStatusEnum = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v10.enums.AdGroupCriterionStatusEnum").msgclass
          AdGroupCriterionStatusEnum::AdGroupCriterionStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v10.enums.AdGroupCriterionStatusEnum.AdGroupCriterionStatus").enummodule
        end
      end
    end
  end
end
