# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v22/enums/hotel_date_selection_type.proto

require 'google/protobuf'


descriptor_data = "\n>google/ads/googleads/v22/enums/hotel_date_selection_type.proto\x12\x1egoogle.ads.googleads.v22.enums\"~\n\x1aHotelDateSelectionTypeEnum\"`\n\x16HotelDateSelectionType\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x0b\n\x07UNKNOWN\x10\x01\x12\x15\n\x11\x44\x45\x46\x41ULT_SELECTION\x10\x32\x12\x11\n\rUSER_SELECTED\x10\x33\x42\xf5\x01\n\"com.google.ads.googleads.v22.enumsB\x1bHotelDateSelectionTypeProtoP\x01ZCgoogle.golang.org/genproto/googleapis/ads/googleads/v22/enums;enums\xa2\x02\x03GAA\xaa\x02\x1eGoogle.Ads.GoogleAds.V22.Enums\xca\x02\x1eGoogle\\Ads\\GoogleAds\\V22\\Enums\xea\x02\"Google::Ads::GoogleAds::V22::Enumsb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Google
  module Ads
    module GoogleAds
      module V22
        module Enums
          HotelDateSelectionTypeEnum = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v22.enums.HotelDateSelectionTypeEnum").msgclass
          HotelDateSelectionTypeEnum::HotelDateSelectionType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v22.enums.HotelDateSelectionTypeEnum.HotelDateSelectionType").enummodule
        end
      end
    end
  end
end
