# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v22/enums/match_type.proto

require 'google/protobuf'


descriptor_data = "\n/google/ads/googleads/v22/enums/match_type.proto\x12\x1egoogle.ads.googleads.v22.enums\"h\n\rMatchTypeEnum\"W\n\tMatchType\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x0b\n\x07UNKNOWN\x10\x01\x12\t\n\x05\x42ROAD\x10\x02\x12\t\n\x05\x45XACT\x10\x03\x12\n\n\x06PHRASE\x10\x04\x12\n\n\x06\x41I_MAX\x10\x05\x42\xe8\x01\n\"com.google.ads.googleads.v22.enumsB\x0eMatchTypeProtoP\x01ZCgoogle.golang.org/genproto/googleapis/ads/googleads/v22/enums;enums\xa2\x02\x03GAA\xaa\x02\x1eGoogle.Ads.GoogleAds.V22.Enums\xca\x02\x1eGoogle\\Ads\\GoogleAds\\V22\\Enums\xea\x02\"Google::Ads::GoogleAds::V22::Enumsb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Google
  module Ads
    module GoogleAds
      module V22
        module Enums
          MatchTypeEnum = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v22.enums.MatchTypeEnum").msgclass
          MatchTypeEnum::MatchType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v22.enums.MatchTypeEnum.MatchType").enummodule
        end
      end
    end
  end
end
