# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v22/enums/parental_status_type.proto

require 'google/protobuf'


descriptor_data = "\n9google/ads/googleads/v22/enums/parental_status_type.proto\x12\x1egoogle.ads.googleads.v22.enums\"\x7f\n\x16ParentalStatusTypeEnum\"e\n\x12ParentalStatusType\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x0b\n\x07UNKNOWN\x10\x01\x12\x0b\n\x06PARENT\x10\xac\x02\x12\x11\n\x0cNOT_A_PARENT\x10\xad\x02\x12\x11\n\x0cUNDETERMINED\x10\xae\x02\x42\xf1\x01\n\"com.google.ads.googleads.v22.enumsB\x17ParentalStatusTypeProtoP\x01ZCgoogle.golang.org/genproto/googleapis/ads/googleads/v22/enums;enums\xa2\x02\x03GAA\xaa\x02\x1eGoogle.Ads.GoogleAds.V22.Enums\xca\x02\x1eGoogle\\Ads\\GoogleAds\\V22\\Enums\xea\x02\"Google::Ads::GoogleAds::V22::Enumsb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Google
  module Ads
    module GoogleAds
      module V22
        module Enums
          ParentalStatusTypeEnum = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v22.enums.ParentalStatusTypeEnum").msgclass
          ParentalStatusTypeEnum::ParentalStatusType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v22.enums.ParentalStatusTypeEnum.ParentalStatusType").enummodule
        end
      end
    end
  end
end
