# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/google_ads/v4/resources/gender_view.proto

require 'google/protobuf'

require 'google/api/field_behavior_pb'
require 'google/api/resource_pb'
require 'google/api/annotations_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "google.ads.googleads.v4.resources.GenderView" do
    optional :resource_name, :string, 1
  end
end

module Google::Ads::GoogleAds::V4::Resources
  GenderView = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v4.resources.GenderView").msgclass
end
