# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/google_ads/v0/services/geo_target_constant_service.proto

require 'google/protobuf'

require 'google/ads/google_ads/v0/resources/geo_target_constant_pb'
require 'google/api/annotations_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "google.ads.googleads.v0.services.GetGeoTargetConstantRequest" do
    optional :resource_name, :string, 1
  end
end

module Google
  module Ads
    module GoogleAds
      module V0
        module Services
          GetGeoTargetConstantRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v0.services.GetGeoTargetConstantRequest").msgclass
        end
      end
    end
  end
end
