# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v23/enums/access_role.proto

require 'google/protobuf'


descriptor_data = "\n0google/ads/googleads/v23/enums/access_role.proto\x12\x1egoogle.ads.googleads.v23.enums\"t\n\x0e\x41\x63\x63\x65ssRoleEnum\"b\n\nAccessRole\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x0b\n\x07UNKNOWN\x10\x01\x12\t\n\x05\x41\x44MIN\x10\x02\x12\x0c\n\x08STANDARD\x10\x03\x12\r\n\tREAD_ONLY\x10\x04\x12\x0e\n\nEMAIL_ONLY\x10\x05\x42\xe9\x01\n\"com.google.ads.googleads.v23.enumsB\x0f\x41\x63\x63\x65ssRoleProtoP\x01ZCgoogle.golang.org/genproto/googleapis/ads/googleads/v23/enums;enums\xa2\x02\x03GAA\xaa\x02\x1eGoogle.Ads.GoogleAds.V23.Enums\xca\x02\x1eGoogle\\Ads\\GoogleAds\\V23\\Enums\xea\x02\"Google::Ads::GoogleAds::V23::Enumsb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Google
  module Ads
    module GoogleAds
      module V23
        module Enums
          AccessRoleEnum = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v23.enums.AccessRoleEnum").msgclass
          AccessRoleEnum::AccessRole = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v23.enums.AccessRoleEnum.AccessRole").enummodule
        end
      end
    end
  end
end
