# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v23/enums/brand_state.proto

require 'google/protobuf'


descriptor_data = "\n0google/ads/googleads/v23/enums/brand_state.proto\x12\x1egoogle.ads.googleads.v23.enums\"\x95\x01\n\x0e\x42randStateEnum\"\x82\x01\n\nBrandState\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x0b\n\x07UNKNOWN\x10\x01\x12\x0b\n\x07\x45NABLED\x10\x02\x12\x0e\n\nDEPRECATED\x10\x03\x12\x0e\n\nUNVERIFIED\x10\x04\x12\x0c\n\x08\x41PPROVED\x10\x05\x12\r\n\tCANCELLED\x10\x06\x12\x0c\n\x08REJECTED\x10\x07\x42\xe9\x01\n\"com.google.ads.googleads.v23.enumsB\x0f\x42randStateProtoP\x01ZCgoogle.golang.org/genproto/googleapis/ads/googleads/v23/enums;enums\xa2\x02\x03GAA\xaa\x02\x1eGoogle.Ads.GoogleAds.V23.Enums\xca\x02\x1eGoogle\\Ads\\GoogleAds\\V23\\Enums\xea\x02\"Google::Ads::GoogleAds::V23::Enumsb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Google
  module Ads
    module GoogleAds
      module V23
        module Enums
          BrandStateEnum = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v23.enums.BrandStateEnum").msgclass
          BrandStateEnum::BrandState = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v23.enums.BrandStateEnum.BrandState").enummodule
        end
      end
    end
  end
end
