# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v23/enums/display_upload_product_type.proto

require 'google/protobuf'


descriptor_data = "\n@google/ads/googleads/v23/enums/display_upload_product_type.proto\x12\x1egoogle.ads.googleads.v23.enums\"\xfc\x02\n\x1c\x44isplayUploadProductTypeEnum\"\xdb\x02\n\x18\x44isplayUploadProductType\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x0b\n\x07UNKNOWN\x10\x01\x12\x13\n\x0fHTML5_UPLOAD_AD\x10\x02\x12\x1e\n\x1a\x44YNAMIC_HTML5_EDUCATION_AD\x10\x03\x12\x1b\n\x17\x44YNAMIC_HTML5_FLIGHT_AD\x10\x04\x12!\n\x1d\x44YNAMIC_HTML5_HOTEL_RENTAL_AD\x10\x05\x12\x18\n\x14\x44YNAMIC_HTML5_JOB_AD\x10\x06\x12\x1a\n\x16\x44YNAMIC_HTML5_LOCAL_AD\x10\x07\x12 \n\x1c\x44YNAMIC_HTML5_REAL_ESTATE_AD\x10\x08\x12\x1b\n\x17\x44YNAMIC_HTML5_CUSTOM_AD\x10\t\x12\x1b\n\x17\x44YNAMIC_HTML5_TRAVEL_AD\x10\n\x12\x1a\n\x16\x44YNAMIC_HTML5_HOTEL_AD\x10\x0b\x42\xf7\x01\n\"com.google.ads.googleads.v23.enumsB\x1d\x44isplayUploadProductTypeProtoP\x01ZCgoogle.golang.org/genproto/googleapis/ads/googleads/v23/enums;enums\xa2\x02\x03GAA\xaa\x02\x1eGoogle.Ads.GoogleAds.V23.Enums\xca\x02\x1eGoogle\\Ads\\GoogleAds\\V23\\Enums\xea\x02\"Google::Ads::GoogleAds::V23::Enumsb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Google
  module Ads
    module GoogleAds
      module V23
        module Enums
          DisplayUploadProductTypeEnum = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v23.enums.DisplayUploadProductTypeEnum").msgclass
          DisplayUploadProductTypeEnum::DisplayUploadProductType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v23.enums.DisplayUploadProductTypeEnum.DisplayUploadProductType").enummodule
        end
      end
    end
  end
end
