# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v20/enums/campaign_primary_status.proto

require 'google/protobuf'


descriptor_data = "\n<google/ads/googleads/v20/enums/campaign_primary_status.proto\x12\x1egoogle.ads.googleads.v20.enums\"\xd2\x01\n\x19\x43\x61mpaignPrimaryStatusEnum\"\xb4\x01\n\x15\x43\x61mpaignPrimaryStatus\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x0b\n\x07UNKNOWN\x10\x01\x12\x0c\n\x08\x45LIGIBLE\x10\x02\x12\n\n\x06PAUSED\x10\x03\x12\x0b\n\x07REMOVED\x10\x04\x12\t\n\x05\x45NDED\x10\x05\x12\x0b\n\x07PENDING\x10\x06\x12\x11\n\rMISCONFIGURED\x10\x07\x12\x0b\n\x07LIMITED\x10\x08\x12\x0c\n\x08LEARNING\x10\t\x12\x10\n\x0cNOT_ELIGIBLE\x10\nB\xf4\x01\n\"com.google.ads.googleads.v20.enumsB\x1a\x43\x61mpaignPrimaryStatusProtoP\x01ZCgoogle.golang.org/genproto/googleapis/ads/googleads/v20/enums;enums\xa2\x02\x03GAA\xaa\x02\x1eGoogle.Ads.GoogleAds.V20.Enums\xca\x02\x1eGoogle\\Ads\\GoogleAds\\V20\\Enums\xea\x02\"Google::Ads::GoogleAds::V20::Enumsb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Google
  module Ads
    module GoogleAds
      module V20
        module Enums
          CampaignPrimaryStatusEnum = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v20.enums.CampaignPrimaryStatusEnum").msgclass
          CampaignPrimaryStatusEnum::CampaignPrimaryStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v20.enums.CampaignPrimaryStatusEnum.CampaignPrimaryStatus").enummodule
        end
      end
    end
  end
end
