# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v15/enums/education_placeholder_field.proto

require 'google/protobuf'


descriptor_data = "\n@google/ads/googleads/v15/enums/education_placeholder_field.proto\x12\x1egoogle.ads.googleads.v15.enums\"\xbf\x03\n\x1d\x45\x64ucationPlaceholderFieldEnum\"\x9d\x03\n\x19\x45\x64ucationPlaceholderField\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x0b\n\x07UNKNOWN\x10\x01\x12\x0e\n\nPROGRAM_ID\x10\x02\x12\x0f\n\x0bLOCATION_ID\x10\x03\x12\x10\n\x0cPROGRAM_NAME\x10\x04\x12\x11\n\rAREA_OF_STUDY\x10\x05\x12\x17\n\x13PROGRAM_DESCRIPTION\x10\x06\x12\x0f\n\x0bSCHOOL_NAME\x10\x07\x12\x0b\n\x07\x41\x44\x44RESS\x10\x08\x12\x17\n\x13THUMBNAIL_IMAGE_URL\x10\t\x12#\n\x1f\x41LTERNATIVE_THUMBNAIL_IMAGE_URL\x10\n\x12\x0e\n\nFINAL_URLS\x10\x0b\x12\x15\n\x11\x46INAL_MOBILE_URLS\x10\x0c\x12\x10\n\x0cTRACKING_URL\x10\r\x12\x17\n\x13\x43ONTEXTUAL_KEYWORDS\x10\x0e\x12\x14\n\x10\x41NDROID_APP_LINK\x10\x0f\x12\x17\n\x13SIMILAR_PROGRAM_IDS\x10\x10\x12\x10\n\x0cIOS_APP_LINK\x10\x11\x12\x14\n\x10IOS_APP_STORE_ID\x10\x12\x42\xf8\x01\n\"com.google.ads.googleads.v15.enumsB\x1e\x45\x64ucationPlaceholderFieldProtoP\x01ZCgoogle.golang.org/genproto/googleapis/ads/googleads/v15/enums;enums\xa2\x02\x03GAA\xaa\x02\x1eGoogle.Ads.GoogleAds.V15.Enums\xca\x02\x1eGoogle\\Ads\\GoogleAds\\V15\\Enums\xea\x02\"Google::Ads::GoogleAds::V15::Enumsb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError => e
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Google
  module Ads
    module GoogleAds
      module V15
        module Enums
          EducationPlaceholderFieldEnum = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v15.enums.EducationPlaceholderFieldEnum").msgclass
          EducationPlaceholderFieldEnum::EducationPlaceholderField = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v15.enums.EducationPlaceholderFieldEnum.EducationPlaceholderField").enummodule
        end
      end
    end
  end
end
