# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v2/enums/price_extension_type.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/ads/googleads/v2/enums/price_extension_type.proto", :syntax => :proto3) do
    add_message "google.ads.googleads.v2.enums.PriceExtensionTypeEnum" do
    end
    add_enum "google.ads.googleads.v2.enums.PriceExtensionTypeEnum.PriceExtensionType" do
      value :UNSPECIFIED, 0
      value :UNKNOWN, 1
      value :BRANDS, 2
      value :EVENTS, 3
      value :LOCATIONS, 4
      value :NEIGHBORHOODS, 5
      value :PRODUCT_CATEGORIES, 6
      value :PRODUCT_TIERS, 7
      value :SERVICES, 8
      value :SERVICE_CATEGORIES, 9
      value :SERVICE_TIERS, 10
    end
  end
end

module Google
  module Ads
    module GoogleAds
      module V2
        module Enums
          PriceExtensionTypeEnum = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v2.enums.PriceExtensionTypeEnum").msgclass
          PriceExtensionTypeEnum::PriceExtensionType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v2.enums.PriceExtensionTypeEnum.PriceExtensionType").enummodule
        end
      end
    end
  end
end
