# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v6/common/offline_user_data.proto

require 'google/protobuf'

require 'google/ads/google_ads/v6/enums/user_identifier_source_pb'
require 'google/api/annotations_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/ads/googleads/v6/common/offline_user_data.proto", :syntax => :proto3) do
    add_message "google.ads.googleads.v6.common.OfflineUserAddressInfo" do
      proto3_optional :hashed_first_name, :string, 7
      proto3_optional :hashed_last_name, :string, 8
      proto3_optional :city, :string, 9
      proto3_optional :state, :string, 10
      proto3_optional :country_code, :string, 11
      proto3_optional :postal_code, :string, 12
    end
    add_message "google.ads.googleads.v6.common.UserIdentifier" do
      optional :user_identifier_source, :enum, 6, "google.ads.googleads.v6.enums.UserIdentifierSourceEnum.UserIdentifierSource"
      oneof :identifier do
        optional :hashed_email, :string, 7
        optional :hashed_phone_number, :string, 8
        optional :mobile_id, :string, 9
        optional :third_party_user_id, :string, 10
        optional :address_info, :message, 5, "google.ads.googleads.v6.common.OfflineUserAddressInfo"
      end
    end
    add_message "google.ads.googleads.v6.common.TransactionAttribute" do
      proto3_optional :transaction_date_time, :string, 8
      proto3_optional :transaction_amount_micros, :double, 9
      proto3_optional :currency_code, :string, 10
      proto3_optional :conversion_action, :string, 11
      proto3_optional :order_id, :string, 12
      optional :store_attribute, :message, 6, "google.ads.googleads.v6.common.StoreAttribute"
      proto3_optional :custom_value, :string, 13
    end
    add_message "google.ads.googleads.v6.common.StoreAttribute" do
      proto3_optional :store_code, :string, 2
    end
    add_message "google.ads.googleads.v6.common.UserData" do
      repeated :user_identifiers, :message, 1, "google.ads.googleads.v6.common.UserIdentifier"
      optional :transaction_attribute, :message, 2, "google.ads.googleads.v6.common.TransactionAttribute"
      optional :user_attribute, :message, 3, "google.ads.googleads.v6.common.UserAttribute"
    end
    add_message "google.ads.googleads.v6.common.UserAttribute" do
      proto3_optional :lifetime_value_micros, :int64, 1
      proto3_optional :lifetime_value_bucket, :int32, 2
    end
    add_message "google.ads.googleads.v6.common.CustomerMatchUserListMetadata" do
      proto3_optional :user_list, :string, 2
    end
    add_message "google.ads.googleads.v6.common.StoreSalesMetadata" do
      proto3_optional :loyalty_fraction, :double, 5
      proto3_optional :transaction_upload_fraction, :double, 6
      proto3_optional :custom_key, :string, 7
      optional :third_party_metadata, :message, 3, "google.ads.googleads.v6.common.StoreSalesThirdPartyMetadata"
    end
    add_message "google.ads.googleads.v6.common.StoreSalesThirdPartyMetadata" do
      proto3_optional :advertiser_upload_date_time, :string, 7
      proto3_optional :valid_transaction_fraction, :double, 8
      proto3_optional :partner_match_fraction, :double, 9
      proto3_optional :partner_upload_fraction, :double, 10
      proto3_optional :bridge_map_version_id, :string, 11
      proto3_optional :partner_id, :int64, 12
    end
  end
end

module Google
  module Ads
    module GoogleAds
      module V6
        module Common
          OfflineUserAddressInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v6.common.OfflineUserAddressInfo").msgclass
          UserIdentifier = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v6.common.UserIdentifier").msgclass
          TransactionAttribute = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v6.common.TransactionAttribute").msgclass
          StoreAttribute = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v6.common.StoreAttribute").msgclass
          UserData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v6.common.UserData").msgclass
          UserAttribute = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v6.common.UserAttribute").msgclass
          CustomerMatchUserListMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v6.common.CustomerMatchUserListMetadata").msgclass
          StoreSalesMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v6.common.StoreSalesMetadata").msgclass
          StoreSalesThirdPartyMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v6.common.StoreSalesThirdPartyMetadata").msgclass
        end
      end
    end
  end
end
