# frozen_string_literal: true

# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!

# require "google/ads/google_ads/error"
require "google/ads/google_ads/v20/services/keyword_plan_idea_service_pb"

module Google
  module Ads
    module GoogleAds
      module V20
        module Services
          module KeywordPlanIdeaService
            ##
            # Client for the KeywordPlanIdeaService service.
            #
            # Service to generate keyword ideas.
            #
            class Client
              # @private
              API_VERSION = ""

              # @private
              DEFAULT_ENDPOINT_TEMPLATE = "googleads.$UNIVERSE_DOMAIN$"

              # @private
              attr_reader :keyword_plan_idea_service_stub

              ##
              # Configure the KeywordPlanIdeaService Client class.
              #
              # See {::Google::Ads::GoogleAds::V20::Services::KeywordPlanIdeaService::Client::Configuration}
              # for a description of the configuration fields.
              #
              # @example
              #
              #   # Modify the configuration for all KeywordPlanIdeaService clients
              #   ::Google::Ads::GoogleAds::V20::Services::KeywordPlanIdeaService::Client.configure do |config|
              #     config.timeout = 10.0
              #   end
              #
              # @yield [config] Configure the Client client.
              # @yieldparam config [Client::Configuration]
              #
              # @return [Client::Configuration]
              #
              def self.configure
                @configure ||= begin
                  default_config = Client::Configuration.new

                  default_config.timeout = 14_400.0
                  default_config.retry_policy = {
                    initial_delay: 5.0, max_delay: 60.0, multiplier: 1.3, retry_codes: [14, 4]
                  }

                  default_config
                end
                yield @configure if block_given?
                @configure
              end

              ##
              # Configure the KeywordPlanIdeaService Client instance.
              #
              # The configuration is set to the derived mode, meaning that values can be changed,
              # but structural changes (adding new fields, etc.) are not allowed. Structural changes
              # should be made on {Client.configure}.
              #
              # See {::Google::Ads::GoogleAds::V20::Services::KeywordPlanIdeaService::Client::Configuration}
              # for a description of the configuration fields.
              #
              # @yield [config] Configure the Client client.
              # @yieldparam config [Client::Configuration]
              #
              # @return [Client::Configuration]
              #
              def configure
                yield @config if block_given?
                @config
              end

              ##
              # The effective universe domain
              #
              # @return [String]
              #
              def universe_domain
                @keyword_plan_idea_service_stub.universe_domain
              end

              ##
              # Create a new KeywordPlanIdeaService client object.
              #
              # @example
              #
              #   # Create a client using the default configuration
              #   client = ::Google::Ads::GoogleAds::V20::Services::KeywordPlanIdeaService::Client.new
              #
              #   # Create a client using a custom configuration
              #   client = ::Google::Ads::GoogleAds::V20::Services::KeywordPlanIdeaService::Client.new do |config|
              #     config.timeout = 10.0
              #   end
              #
              # @yield [config] Configure the KeywordPlanIdeaService client.
              # @yieldparam config [Client::Configuration]
              #
              def initialize
                # These require statements are intentionally placed here to initialize
                # the gRPC module only when it's required.
                # See https://github.com/googleapis/toolkit/issues/446
                require "gapic/grpc"
                require "google/ads/google_ads/v20/services/keyword_plan_idea_service_services_pb"

                # Create the configuration object
                @config = Configuration.new Client.configure

                # Yield the configuration if needed
                yield @config if block_given?

                # Create credentials
                credentials = @config.credentials
                # Use self-signed JWT if the endpoint is unchanged from default,
                # but only if the default endpoint does not have a region prefix.
                enable_self_signed_jwt = @config.endpoint.nil? ||
                                         (@config.endpoint == Configuration::DEFAULT_ENDPOINT &&
                                         !@config.endpoint.split(".").first.include?("-"))
                credentials ||= Credentials.default scope: @config.scope,
                                                    enable_self_signed_jwt: enable_self_signed_jwt
                if credentials.is_a?(::String) || credentials.is_a?(::Hash)
                  credentials = Credentials.new credentials, scope: @config.scope
                end
                @quota_project_id = @config.quota_project
                @quota_project_id ||= credentials.quota_project_id if credentials.respond_to? :quota_project_id

                @keyword_plan_idea_service_stub = ::Gapic::ServiceStub.new(
                  ::Google::Ads::GoogleAds::V20::Services::KeywordPlanIdeaService::Stub,
                  credentials: credentials,
                  endpoint: @config.endpoint,
                  endpoint_template: DEFAULT_ENDPOINT_TEMPLATE,
                  universe_domain: @config.universe_domain,
                  channel_args: @config.channel_args,
                  interceptors: @config.interceptors,
                  channel_pool_config: @config.channel_pool,
                  logger: @config.logger
                )

                @keyword_plan_idea_service_stub.stub_logger&.info do |entry|
                  entry.set_system_name
                  entry.set_service
                  entry.message = "Created client for #{entry.service}"
                  entry.set_credentials_fields credentials
                  entry.set "customEndpoint", @config.endpoint if @config.endpoint
                  entry.set "defaultTimeout", @config.timeout if @config.timeout
                  entry.set "quotaProject", @quota_project_id if @quota_project_id
                end
              end

              ##
              # The logger used for request/response debug logging.
              #
              # @return [Logger]
              #
              def logger
                @keyword_plan_idea_service_stub.logger
              end

              # Service calls

              ##
              # Returns a list of keyword ideas.
              #
              # List of thrown errors:
              #   [AuthenticationError]()
              #   [AuthorizationError]()
              #   [CollectionSizeError]()
              #   [HeaderError]()
              #   [InternalError]()
              #   [KeywordPlanIdeaError]()
              #   [QuotaError]()
              #   [RequestError]()
              #
              # @overload generate_keyword_ideas(request, options = nil)
              #   Pass arguments to `generate_keyword_ideas` via a request object, either of type
              #   {::Google::Ads::GoogleAds::V20::Services::GenerateKeywordIdeasRequest} or an equivalent Hash.
              #
              #   @param request [::Google::Ads::GoogleAds::V20::Services::GenerateKeywordIdeasRequest, ::Hash]
              #     A request object representing the call parameters. Required. To specify no
              #     parameters, or to keep all the default parameter values, pass an empty Hash.
              #   @param options [::Gapic::CallOptions, ::Hash]
              #     Overrides the default settings for this call, e.g, timeout, retries, etc. Optional.
              #
              # @overload generate_keyword_ideas(customer_id: nil, language: nil, geo_target_constants: nil, include_adult_keywords: nil, page_token: nil, page_size: nil, keyword_plan_network: nil, keyword_annotation: nil, aggregate_metrics: nil, historical_metrics_options: nil, keyword_and_url_seed: nil, keyword_seed: nil, url_seed: nil, site_seed: nil)
              #   Pass arguments to `generate_keyword_ideas` via keyword arguments. Note that at
              #   least one keyword argument is required. To specify no parameters, or to keep all
              #   the default parameter values, pass an empty Hash as a request object (see above).
              #
              #   @param customer_id [::String]
              #     The ID of the customer with the recommendation.
              #   @param language [::String]
              #     The resource name of the language to target.
              #     Each keyword belongs to some set of languages; a keyword is included if
              #     language is one of its languages.
              #     If not set, all keywords will be included.
              #   @param geo_target_constants [::Array<::String>]
              #     The resource names of the location to target. Maximum is 10.
              #     An empty list MAY be used to specify all targeting geos.
              #   @param include_adult_keywords [::Boolean]
              #     If true, adult keywords will be included in response.
              #     The default value is false.
              #   @param page_token [::String]
              #     Token of the page to retrieve. If not specified, the first
              #     page of results will be returned. To request next page of results use the
              #     value obtained from `next_page_token` in the previous response.
              #     The request fields must match across pages.
              #   @param page_size [::Integer]
              #     Number of results to retrieve in a single page.
              #     A maximum of 10,000 results may be returned, if the page_size
              #     exceeds this, it is ignored.
              #     If unspecified, at most 10,000 results will be returned.
              #     The server may decide to further limit the number of returned resources.
              #     If the response contains fewer than 10,000 results it may not be assumed
              #     as last page of results.
              #   @param keyword_plan_network [::Google::Ads::GoogleAds::V20::Enums::KeywordPlanNetworkEnum::KeywordPlanNetwork]
              #     Targeting network.
              #     If not set, Google Search And Partners Network will be used.
              #   @param keyword_annotation [::Array<::Google::Ads::GoogleAds::V20::Enums::KeywordPlanKeywordAnnotationEnum::KeywordPlanKeywordAnnotation>]
              #     The keyword annotations to include in response.
              #   @param aggregate_metrics [::Google::Ads::GoogleAds::V20::Common::KeywordPlanAggregateMetrics, ::Hash]
              #     The aggregate fields to include in response.
              #   @param historical_metrics_options [::Google::Ads::GoogleAds::V20::Common::HistoricalMetricsOptions, ::Hash]
              #     The options for historical metrics data.
              #   @param keyword_and_url_seed [::Google::Ads::GoogleAds::V20::Services::KeywordAndUrlSeed, ::Hash]
              #     A Keyword and a specific Url to generate ideas from
              #     for example, cars, www.example.com/cars.
              #
              #     Note: The following fields are mutually exclusive: `keyword_and_url_seed`, `keyword_seed`, `url_seed`, `site_seed`. If a field in that set is populated, all other fields in the set will automatically be cleared.
              #   @param keyword_seed [::Google::Ads::GoogleAds::V20::Services::KeywordSeed, ::Hash]
              #     A Keyword or phrase to generate ideas from, for example, cars.
              #
              #     Note: The following fields are mutually exclusive: `keyword_seed`, `keyword_and_url_seed`, `url_seed`, `site_seed`. If a field in that set is populated, all other fields in the set will automatically be cleared.
              #   @param url_seed [::Google::Ads::GoogleAds::V20::Services::UrlSeed, ::Hash]
              #     A specific url to generate ideas from, for example, www.example.com/cars.
              #
              #     Note: The following fields are mutually exclusive: `url_seed`, `keyword_and_url_seed`, `keyword_seed`, `site_seed`. If a field in that set is populated, all other fields in the set will automatically be cleared.
              #   @param site_seed [::Google::Ads::GoogleAds::V20::Services::SiteSeed, ::Hash]
              #     The site to generate ideas from, for example, www.example.com.
              #
              #     Note: The following fields are mutually exclusive: `site_seed`, `keyword_and_url_seed`, `keyword_seed`, `url_seed`. If a field in that set is populated, all other fields in the set will automatically be cleared.
              #
              # @yield [response, operation] Access the result along with the RPC operation
              # @yieldparam response [::Gapic::PagedEnumerable<::Google::Ads::GoogleAds::V20::Services::GenerateKeywordIdeaResult>]
              # @yieldparam operation [::GRPC::ActiveCall::Operation]
              #
              # @return [::Gapic::PagedEnumerable<::Google::Ads::GoogleAds::V20::Services::GenerateKeywordIdeaResult>]
              #
              # @raise [Google::Ads::GoogleAds::Error] if the RPC is aborted.
              #
              # @example Basic example
              #   require "google/ads/google_ads/v20/services"
              #
              #   # Create a client object. The client can be reused for multiple calls.
              #   client = Google::Ads::GoogleAds::V20::Services::KeywordPlanIdeaService::Client.new
              #
              #   # Create a request. To set request fields, pass in keyword arguments.
              #   request = Google::Ads::GoogleAds::V20::Services::GenerateKeywordIdeasRequest.new
              #
              #   # Call the generate_keyword_ideas method.
              #   result = client.generate_keyword_ideas request
              #
              #   # The returned object is of type Gapic::PagedEnumerable. You can iterate
              #   # over elements, and API calls will be issued to fetch pages as needed.
              #   result.each do |item|
              #     # Each element is of type ::Google::Ads::GoogleAds::V20::Services::GenerateKeywordIdeaResult.
              #     p item
              #   end
              #
              def generate_keyword_ideas request, options = nil
                raise ::ArgumentError, "request must be provided" if request.nil?

                request = ::Gapic::Protobuf.coerce request,
                                                   to: ::Google::Ads::GoogleAds::V20::Services::GenerateKeywordIdeasRequest

                # Converts hash and nil to an options object
                options = ::Gapic::CallOptions.new(**options.to_h) if options.respond_to? :to_h

                # Customize the options with defaults
                metadata = @config.rpcs.generate_keyword_ideas.metadata.to_h

                # Set x-goog-api-client, x-goog-user-project and x-goog-api-version headers
                metadata[:"x-goog-api-client"] ||= ::Gapic::Headers.x_goog_api_client \
                  lib_name: @config.lib_name, lib_version: @config.lib_version,
                  gapic_version: ::Google::Ads::GoogleAds::VERSION
                metadata[:"x-goog-api-version"] = API_VERSION unless API_VERSION.empty?
                metadata[:"x-goog-user-project"] = @quota_project_id if @quota_project_id

                header_params = {}
                if request.customer_id
                  header_params["customer_id"] = request.customer_id
                end

                request_params_header = header_params.map { |k, v| "#{k}=#{v}" }.join("&")
                metadata[:"x-goog-request-params"] ||= request_params_header

                options.apply_defaults timeout:      @config.rpcs.generate_keyword_ideas.timeout,
                                       metadata:     metadata,
                                       retry_policy: @config.rpcs.generate_keyword_ideas.retry_policy

                options.apply_defaults timeout:      @config.timeout,
                                       metadata:     @config.metadata,
                                       retry_policy: @config.retry_policy

                @keyword_plan_idea_service_stub.call_rpc :generate_keyword_ideas, request,
                                                         options: options do |response, operation|
                  response = ::Gapic::PagedEnumerable.new @keyword_plan_idea_service_stub, :generate_keyword_ideas,
                                                          request, response, operation, options
                  yield response, operation if block_given?
                  throw :response, response
                end
                # rescue GRPC::BadStatus => grpc_error
                #  raise Google::Ads::GoogleAds::Error.new grpc_error.message
              end

              ##
              # Returns a list of keyword historical metrics.
              #
              # List of thrown errors:
              #   [AuthenticationError]()
              #   [AuthorizationError]()
              #   [CollectionSizeError]()
              #   [HeaderError]()
              #   [InternalError]()
              #   [QuotaError]()
              #   [RequestError]()
              #
              # @overload generate_keyword_historical_metrics(request, options = nil)
              #   Pass arguments to `generate_keyword_historical_metrics` via a request object, either of type
              #   {::Google::Ads::GoogleAds::V20::Services::GenerateKeywordHistoricalMetricsRequest} or an equivalent Hash.
              #
              #   @param request [::Google::Ads::GoogleAds::V20::Services::GenerateKeywordHistoricalMetricsRequest, ::Hash]
              #     A request object representing the call parameters. Required. To specify no
              #     parameters, or to keep all the default parameter values, pass an empty Hash.
              #   @param options [::Gapic::CallOptions, ::Hash]
              #     Overrides the default settings for this call, e.g, timeout, retries, etc. Optional.
              #
              # @overload generate_keyword_historical_metrics(customer_id: nil, keywords: nil, language: nil, include_adult_keywords: nil, geo_target_constants: nil, keyword_plan_network: nil, aggregate_metrics: nil, historical_metrics_options: nil)
              #   Pass arguments to `generate_keyword_historical_metrics` via keyword arguments. Note that at
              #   least one keyword argument is required. To specify no parameters, or to keep all
              #   the default parameter values, pass an empty Hash as a request object (see above).
              #
              #   @param customer_id [::String]
              #     The ID of the customer with the recommendation.
              #   @param keywords [::Array<::String>]
              #     A list of keywords to get historical metrics.
              #     Not all inputs will be returned as a result of near-exact deduplication.
              #     For example, if stats for "car" and "cars" are requested, only "car" will
              #     be returned.
              #     A maximum of 10,000 keywords can be used.
              #   @param language [::String]
              #     The resource name of the language to target.
              #     Each keyword belongs to some set of languages; a keyword is included if
              #     language is one of its languages.
              #     If not set, all keywords will be included.
              #   @param include_adult_keywords [::Boolean]
              #     If true, adult keywords will be included in response.
              #     The default value is false.
              #   @param geo_target_constants [::Array<::String>]
              #     The resource names of the location to target. Maximum is 10.
              #     An empty list MAY be used to specify all targeting geos.
              #   @param keyword_plan_network [::Google::Ads::GoogleAds::V20::Enums::KeywordPlanNetworkEnum::KeywordPlanNetwork]
              #     Targeting network.
              #     If not set, Google Search And Partners Network will be used.
              #   @param aggregate_metrics [::Google::Ads::GoogleAds::V20::Common::KeywordPlanAggregateMetrics, ::Hash]
              #     The aggregate fields to include in response.
              #   @param historical_metrics_options [::Google::Ads::GoogleAds::V20::Common::HistoricalMetricsOptions, ::Hash]
              #     The options for historical metrics data.
              #
              # @yield [response, operation] Access the result along with the RPC operation
              # @yieldparam response [::Google::Ads::GoogleAds::V20::Services::GenerateKeywordHistoricalMetricsResponse]
              # @yieldparam operation [::GRPC::ActiveCall::Operation]
              #
              # @return [::Google::Ads::GoogleAds::V20::Services::GenerateKeywordHistoricalMetricsResponse]
              #
              # @raise [Google::Ads::GoogleAds::Error] if the RPC is aborted.
              #
              # @example Basic example
              #   require "google/ads/google_ads/v20/services"
              #
              #   # Create a client object. The client can be reused for multiple calls.
              #   client = Google::Ads::GoogleAds::V20::Services::KeywordPlanIdeaService::Client.new
              #
              #   # Create a request. To set request fields, pass in keyword arguments.
              #   request = Google::Ads::GoogleAds::V20::Services::GenerateKeywordHistoricalMetricsRequest.new
              #
              #   # Call the generate_keyword_historical_metrics method.
              #   result = client.generate_keyword_historical_metrics request
              #
              #   # The returned object is of type Google::Ads::GoogleAds::V20::Services::GenerateKeywordHistoricalMetricsResponse.
              #   p result
              #
              def generate_keyword_historical_metrics request, options = nil
                raise ::ArgumentError, "request must be provided" if request.nil?

                request = ::Gapic::Protobuf.coerce request,
                                                   to: ::Google::Ads::GoogleAds::V20::Services::GenerateKeywordHistoricalMetricsRequest

                # Converts hash and nil to an options object
                options = ::Gapic::CallOptions.new(**options.to_h) if options.respond_to? :to_h

                # Customize the options with defaults
                metadata = @config.rpcs.generate_keyword_historical_metrics.metadata.to_h

                # Set x-goog-api-client, x-goog-user-project and x-goog-api-version headers
                metadata[:"x-goog-api-client"] ||= ::Gapic::Headers.x_goog_api_client \
                  lib_name: @config.lib_name, lib_version: @config.lib_version,
                  gapic_version: ::Google::Ads::GoogleAds::VERSION
                metadata[:"x-goog-api-version"] = API_VERSION unless API_VERSION.empty?
                metadata[:"x-goog-user-project"] = @quota_project_id if @quota_project_id

                header_params = {}
                if request.customer_id
                  header_params["customer_id"] = request.customer_id
                end

                request_params_header = header_params.map { |k, v| "#{k}=#{v}" }.join("&")
                metadata[:"x-goog-request-params"] ||= request_params_header

                options.apply_defaults timeout:      @config.rpcs.generate_keyword_historical_metrics.timeout,
                                       metadata:     metadata,
                                       retry_policy: @config.rpcs.generate_keyword_historical_metrics.retry_policy

                options.apply_defaults timeout:      @config.timeout,
                                       metadata:     @config.metadata,
                                       retry_policy: @config.retry_policy

                @keyword_plan_idea_service_stub.call_rpc :generate_keyword_historical_metrics, request,
                                                         options: options do |response, operation|
                  yield response, operation if block_given?
                end
                # rescue GRPC::BadStatus => grpc_error
                #  raise Google::Ads::GoogleAds::Error.new grpc_error.message
              end

              ##
              # Returns a list of suggested AdGroups and suggested modifications
              # (text, match type) for the given keywords.
              #
              # List of thrown errors:
              #   [AuthenticationError]()
              #   [AuthorizationError]()
              #   [CollectionSizeError]()
              #   [HeaderError]()
              #   [InternalError]()
              #   [QuotaError]()
              #   [RequestError]()
              #
              # @overload generate_ad_group_themes(request, options = nil)
              #   Pass arguments to `generate_ad_group_themes` via a request object, either of type
              #   {::Google::Ads::GoogleAds::V20::Services::GenerateAdGroupThemesRequest} or an equivalent Hash.
              #
              #   @param request [::Google::Ads::GoogleAds::V20::Services::GenerateAdGroupThemesRequest, ::Hash]
              #     A request object representing the call parameters. Required. To specify no
              #     parameters, or to keep all the default parameter values, pass an empty Hash.
              #   @param options [::Gapic::CallOptions, ::Hash]
              #     Overrides the default settings for this call, e.g, timeout, retries, etc. Optional.
              #
              # @overload generate_ad_group_themes(customer_id: nil, keywords: nil, ad_groups: nil)
              #   Pass arguments to `generate_ad_group_themes` via keyword arguments. Note that at
              #   least one keyword argument is required. To specify no parameters, or to keep all
              #   the default parameter values, pass an empty Hash as a request object (see above).
              #
              #   @param customer_id [::String]
              #     Required. The ID of the customer.
              #   @param keywords [::Array<::String>]
              #     Required. A list of keywords to group into the provided AdGroups.
              #   @param ad_groups [::Array<::String>]
              #     Required. A list of resource names of AdGroups to group keywords into.
              #      Resource name format: `customers/{customer_id}/adGroups/{ad_group_id}`
              #
              # @yield [response, operation] Access the result along with the RPC operation
              # @yieldparam response [::Google::Ads::GoogleAds::V20::Services::GenerateAdGroupThemesResponse]
              # @yieldparam operation [::GRPC::ActiveCall::Operation]
              #
              # @return [::Google::Ads::GoogleAds::V20::Services::GenerateAdGroupThemesResponse]
              #
              # @raise [Google::Ads::GoogleAds::Error] if the RPC is aborted.
              #
              # @example Basic example
              #   require "google/ads/google_ads/v20/services"
              #
              #   # Create a client object. The client can be reused for multiple calls.
              #   client = Google::Ads::GoogleAds::V20::Services::KeywordPlanIdeaService::Client.new
              #
              #   # Create a request. To set request fields, pass in keyword arguments.
              #   request = Google::Ads::GoogleAds::V20::Services::GenerateAdGroupThemesRequest.new
              #
              #   # Call the generate_ad_group_themes method.
              #   result = client.generate_ad_group_themes request
              #
              #   # The returned object is of type Google::Ads::GoogleAds::V20::Services::GenerateAdGroupThemesResponse.
              #   p result
              #
              def generate_ad_group_themes request, options = nil
                raise ::ArgumentError, "request must be provided" if request.nil?

                request = ::Gapic::Protobuf.coerce request,
                                                   to: ::Google::Ads::GoogleAds::V20::Services::GenerateAdGroupThemesRequest

                # Converts hash and nil to an options object
                options = ::Gapic::CallOptions.new(**options.to_h) if options.respond_to? :to_h

                # Customize the options with defaults
                metadata = @config.rpcs.generate_ad_group_themes.metadata.to_h

                # Set x-goog-api-client, x-goog-user-project and x-goog-api-version headers
                metadata[:"x-goog-api-client"] ||= ::Gapic::Headers.x_goog_api_client \
                  lib_name: @config.lib_name, lib_version: @config.lib_version,
                  gapic_version: ::Google::Ads::GoogleAds::VERSION
                metadata[:"x-goog-api-version"] = API_VERSION unless API_VERSION.empty?
                metadata[:"x-goog-user-project"] = @quota_project_id if @quota_project_id

                header_params = {}
                if request.customer_id
                  header_params["customer_id"] = request.customer_id
                end

                request_params_header = header_params.map { |k, v| "#{k}=#{v}" }.join("&")
                metadata[:"x-goog-request-params"] ||= request_params_header

                options.apply_defaults timeout:      @config.rpcs.generate_ad_group_themes.timeout,
                                       metadata:     metadata,
                                       retry_policy: @config.rpcs.generate_ad_group_themes.retry_policy

                options.apply_defaults timeout:      @config.timeout,
                                       metadata:     @config.metadata,
                                       retry_policy: @config.retry_policy

                @keyword_plan_idea_service_stub.call_rpc :generate_ad_group_themes, request,
                                                         options: options do |response, operation|
                  yield response, operation if block_given?
                end
                # rescue GRPC::BadStatus => grpc_error
                #  raise Google::Ads::GoogleAds::Error.new grpc_error.message
              end

              ##
              # Returns metrics (such as impressions, clicks, total cost) of a keyword
              # forecast for the given campaign.
              #
              # List of thrown errors:
              #   [AuthenticationError]()
              #   [AuthorizationError]()
              #   [CollectionSizeError]()
              #   [HeaderError]()
              #   [InternalError]()
              #   [QuotaError]()
              #   [RequestError]()
              #
              # @overload generate_keyword_forecast_metrics(request, options = nil)
              #   Pass arguments to `generate_keyword_forecast_metrics` via a request object, either of type
              #   {::Google::Ads::GoogleAds::V20::Services::GenerateKeywordForecastMetricsRequest} or an equivalent Hash.
              #
              #   @param request [::Google::Ads::GoogleAds::V20::Services::GenerateKeywordForecastMetricsRequest, ::Hash]
              #     A request object representing the call parameters. Required. To specify no
              #     parameters, or to keep all the default parameter values, pass an empty Hash.
              #   @param options [::Gapic::CallOptions, ::Hash]
              #     Overrides the default settings for this call, e.g, timeout, retries, etc. Optional.
              #
              # @overload generate_keyword_forecast_metrics(customer_id: nil, currency_code: nil, forecast_period: nil, campaign: nil)
              #   Pass arguments to `generate_keyword_forecast_metrics` via keyword arguments. Note that at
              #   least one keyword argument is required. To specify no parameters, or to keep all
              #   the default parameter values, pass an empty Hash as a request object (see above).
              #
              #   @param customer_id [::String]
              #     The ID of the customer.
              #   @param currency_code [::String]
              #     The currency used for exchange rate conversion.
              #     By default, the account currency of the customer is used.
              #     Set this field only if the currency is different from the account currency.
              #     The list of valid currency codes can be found at
              #     https://developers.google.com/google-ads/api/data/codes-formats#currency-codes.
              #   @param forecast_period [::Google::Ads::GoogleAds::V20::Common::DateRange, ::Hash]
              #     The date range for the forecast. The start date must be in the future and
              #     end date must be within 1 year from today. The reference timezone used is
              #     the one of the Google Ads account belonging to the customer. If not set, a
              #     default date range from next Sunday to the following Saturday will be used.
              #   @param campaign [::Google::Ads::GoogleAds::V20::Services::CampaignToForecast, ::Hash]
              #     Required. The campaign used in the forecast.
              #
              # @yield [response, operation] Access the result along with the RPC operation
              # @yieldparam response [::Google::Ads::GoogleAds::V20::Services::GenerateKeywordForecastMetricsResponse]
              # @yieldparam operation [::GRPC::ActiveCall::Operation]
              #
              # @return [::Google::Ads::GoogleAds::V20::Services::GenerateKeywordForecastMetricsResponse]
              #
              # @raise [Google::Ads::GoogleAds::Error] if the RPC is aborted.
              #
              # @example Basic example
              #   require "google/ads/google_ads/v20/services"
              #
              #   # Create a client object. The client can be reused for multiple calls.
              #   client = Google::Ads::GoogleAds::V20::Services::KeywordPlanIdeaService::Client.new
              #
              #   # Create a request. To set request fields, pass in keyword arguments.
              #   request = Google::Ads::GoogleAds::V20::Services::GenerateKeywordForecastMetricsRequest.new
              #
              #   # Call the generate_keyword_forecast_metrics method.
              #   result = client.generate_keyword_forecast_metrics request
              #
              #   # The returned object is of type Google::Ads::GoogleAds::V20::Services::GenerateKeywordForecastMetricsResponse.
              #   p result
              #
              def generate_keyword_forecast_metrics request, options = nil
                raise ::ArgumentError, "request must be provided" if request.nil?

                request = ::Gapic::Protobuf.coerce request,
                                                   to: ::Google::Ads::GoogleAds::V20::Services::GenerateKeywordForecastMetricsRequest

                # Converts hash and nil to an options object
                options = ::Gapic::CallOptions.new(**options.to_h) if options.respond_to? :to_h

                # Customize the options with defaults
                metadata = @config.rpcs.generate_keyword_forecast_metrics.metadata.to_h

                # Set x-goog-api-client, x-goog-user-project and x-goog-api-version headers
                metadata[:"x-goog-api-client"] ||= ::Gapic::Headers.x_goog_api_client \
                  lib_name: @config.lib_name, lib_version: @config.lib_version,
                  gapic_version: ::Google::Ads::GoogleAds::VERSION
                metadata[:"x-goog-api-version"] = API_VERSION unless API_VERSION.empty?
                metadata[:"x-goog-user-project"] = @quota_project_id if @quota_project_id

                header_params = {}
                if request.customer_id
                  header_params["customer_id"] = request.customer_id
                end

                request_params_header = header_params.map { |k, v| "#{k}=#{v}" }.join("&")
                metadata[:"x-goog-request-params"] ||= request_params_header

                options.apply_defaults timeout:      @config.rpcs.generate_keyword_forecast_metrics.timeout,
                                       metadata:     metadata,
                                       retry_policy: @config.rpcs.generate_keyword_forecast_metrics.retry_policy

                options.apply_defaults timeout:      @config.timeout,
                                       metadata:     @config.metadata,
                                       retry_policy: @config.retry_policy

                @keyword_plan_idea_service_stub.call_rpc :generate_keyword_forecast_metrics, request,
                                                         options: options do |response, operation|
                  yield response, operation if block_given?
                end
                # rescue GRPC::BadStatus => grpc_error
                #  raise Google::Ads::GoogleAds::Error.new grpc_error.message
              end

              ##
              # Configuration class for the KeywordPlanIdeaService API.
              #
              # This class represents the configuration for KeywordPlanIdeaService,
              # providing control over timeouts, retry behavior, logging, transport
              # parameters, and other low-level controls. Certain parameters can also be
              # applied individually to specific RPCs. See
              # {::Google::Ads::GoogleAds::V20::Services::KeywordPlanIdeaService::Client::Configuration::Rpcs}
              # for a list of RPCs that can be configured independently.
              #
              # Configuration can be applied globally to all clients, or to a single client
              # on construction.
              #
              # @example
              #
              #   # Modify the global config, setting the timeout for
              #   # generate_keyword_ideas to 20 seconds,
              #   # and all remaining timeouts to 10 seconds.
              #   ::Google::Ads::GoogleAds::V20::Services::KeywordPlanIdeaService::Client.configure do |config|
              #     config.timeout = 10.0
              #     config.rpcs.generate_keyword_ideas.timeout = 20.0
              #   end
              #
              #   # Apply the above configuration only to a new client.
              #   client = ::Google::Ads::GoogleAds::V20::Services::KeywordPlanIdeaService::Client.new do |config|
              #     config.timeout = 10.0
              #     config.rpcs.generate_keyword_ideas.timeout = 20.0
              #   end
              #
              # @!attribute [rw] endpoint
              #   A custom service endpoint, as a hostname or hostname:port. The default is
              #   nil, indicating to use the default endpoint in the current universe domain.
              #   @return [::String,nil]
              # @!attribute [rw] credentials
              #   Credentials to send with calls. You may provide any of the following types:
              #    *  (`String`) The path to a service account key file in JSON format
              #    *  (`Hash`) A service account key as a Hash
              #    *  (`Google::Auth::Credentials`) A googleauth credentials object
              #       (see the [googleauth docs](https://rubydoc.info/gems/googleauth/Google/Auth/Credentials))
              #    *  (`Signet::OAuth2::Client`) A signet oauth2 client object
              #       (see the [signet docs](https://rubydoc.info/gems/signet/Signet/OAuth2/Client))
              #    *  (`GRPC::Core::Channel`) a gRPC channel with included credentials
              #    *  (`GRPC::Core::ChannelCredentials`) a gRPC credentails object
              #    *  (`nil`) indicating no credentials
              #
              #   Warning: If you accept a credential configuration (JSON file or Hash) from an
              #   external source for authentication to Google Cloud, you must validate it before
              #   providing it to a Google API client library. Providing an unvalidated credential
              #   configuration to Google APIs can compromise the security of your systems and data.
              #   For more information, refer to [Validate credential configurations from external
              #   sources](https://cloud.google.com/docs/authentication/external/externally-sourced-credentials).
              #   @return [::Object]
              # @!attribute [rw] scope
              #   The OAuth scopes
              #   @return [::Array<::String>]
              # @!attribute [rw] lib_name
              #   The library name as recorded in instrumentation and logging
              #   @return [::String]
              # @!attribute [rw] lib_version
              #   The library version as recorded in instrumentation and logging
              #   @return [::String]
              # @!attribute [rw] channel_args
              #   Extra parameters passed to the gRPC channel. Note: this is ignored if a
              #   `GRPC::Core::Channel` object is provided as the credential.
              #   @return [::Hash]
              # @!attribute [rw] interceptors
              #   An array of interceptors that are run before calls are executed.
              #   @return [::Array<::GRPC::ClientInterceptor>]
              # @!attribute [rw] timeout
              #   The call timeout in seconds.
              #   @return [::Numeric]
              # @!attribute [rw] metadata
              #   Additional gRPC headers to be sent with the call.
              #   @return [::Hash{::Symbol=>::String}]
              # @!attribute [rw] retry_policy
              #   The retry policy. The value is a hash with the following keys:
              #    *  `:initial_delay` (*type:* `Numeric`) - The initial delay in seconds.
              #    *  `:max_delay` (*type:* `Numeric`) - The max delay in seconds.
              #    *  `:multiplier` (*type:* `Numeric`) - The incremental backoff multiplier.
              #    *  `:retry_codes` (*type:* `Array<String>`) - The error codes that should
              #       trigger a retry.
              #   @return [::Hash]
              # @!attribute [rw] quota_project
              #   A separate project against which to charge quota.
              #   @return [::String]
              # @!attribute [rw] universe_domain
              #   The universe domain within which to make requests. This determines the
              #   default endpoint URL. The default value of nil uses the environment
              #   universe (usually the default "googleapis.com" universe).
              #   @return [::String,nil]
              # @!attribute [rw] logger
              #   A custom logger to use for request/response debug logging, or the value
              #   `:default` (the default) to construct a default logger, or `nil` to
              #   explicitly disable logging.
              #   @return [::Logger,:default,nil]
              #
              class Configuration
                extend ::Gapic::Config

                # @private
                # The endpoint specific to the default "googleapis.com" universe. Deprecated.
                DEFAULT_ENDPOINT = "googleads.googleapis.com"

                config_attr :endpoint,      nil, ::String, nil
                config_attr :credentials,   nil do |value|
                  allowed = [::String, ::Hash, ::Proc, ::Symbol, ::Google::Auth::Credentials,
                             ::Google::Auth::BaseClient, ::Signet::OAuth2::Client, nil]
                  allowed += [::GRPC::Core::Channel, ::GRPC::Core::ChannelCredentials] if defined? ::GRPC::Core::Channel
                  allowed.any? { |klass| klass === value }
                end
                config_attr :scope,         nil, ::String, ::Array, nil
                config_attr :lib_name,      nil, ::String, nil
                config_attr :lib_version,   nil, ::String, nil
                config_attr(:channel_args,  { "grpc.service_config_disable_resolution" => 1 }, ::Hash, nil)
                config_attr :interceptors,  nil, ::Array, nil
                config_attr :timeout,       nil, ::Numeric, nil
                config_attr :metadata,      nil, ::Hash, nil
                config_attr :retry_policy,  nil, ::Hash, ::Proc, nil
                config_attr :quota_project, nil, ::String, nil
                config_attr :universe_domain, nil, ::String, nil
                config_attr :logger, :default, ::Logger, nil, :default

                # @private
                def initialize parent_config = nil
                  @parent_config = parent_config unless parent_config.nil?

                  yield self if block_given?
                end

                ##
                # Configurations for individual RPCs
                # @return [Rpcs]
                #
                def rpcs
                  @rpcs ||= begin
                    parent_rpcs = nil
                    parent_rpcs = @parent_config.rpcs if defined?(@parent_config) && @parent_config.respond_to?(:rpcs)
                    Rpcs.new parent_rpcs
                  end
                end

                ##
                # Configuration for the channel pool
                # @return [::Gapic::ServiceStub::ChannelPool::Configuration]
                #
                def channel_pool
                  @channel_pool ||= ::Gapic::ServiceStub::ChannelPool::Configuration.new
                end

                ##
                # Configuration RPC class for the KeywordPlanIdeaService API.
                #
                # Includes fields providing the configuration for each RPC in this service.
                # Each configuration object is of type `Gapic::Config::Method` and includes
                # the following configuration fields:
                #
                #  *  `timeout` (*type:* `Numeric`) - The call timeout in seconds
                #  *  `metadata` (*type:* `Hash{Symbol=>String}`) - Additional gRPC headers
                #  *  `retry_policy (*type:* `Hash`) - The retry policy. The policy fields
                #     include the following keys:
                #      *  `:initial_delay` (*type:* `Numeric`) - The initial delay in seconds.
                #      *  `:max_delay` (*type:* `Numeric`) - The max delay in seconds.
                #      *  `:multiplier` (*type:* `Numeric`) - The incremental backoff multiplier.
                #      *  `:retry_codes` (*type:* `Array<String>`) - The error codes that should
                #         trigger a retry.
                #
                class Rpcs
                  ##
                  # RPC-specific configuration for `generate_keyword_ideas`
                  # @return [::Gapic::Config::Method]
                  #
                  attr_reader :generate_keyword_ideas
                  ##
                  # RPC-specific configuration for `generate_keyword_historical_metrics`
                  # @return [::Gapic::Config::Method]
                  #
                  attr_reader :generate_keyword_historical_metrics
                  ##
                  # RPC-specific configuration for `generate_ad_group_themes`
                  # @return [::Gapic::Config::Method]
                  #
                  attr_reader :generate_ad_group_themes
                  ##
                  # RPC-specific configuration for `generate_keyword_forecast_metrics`
                  # @return [::Gapic::Config::Method]
                  #
                  attr_reader :generate_keyword_forecast_metrics

                  # @private
                  def initialize parent_rpcs = nil
                    generate_keyword_ideas_config = parent_rpcs.generate_keyword_ideas if parent_rpcs.respond_to? :generate_keyword_ideas
                    @generate_keyword_ideas = ::Gapic::Config::Method.new generate_keyword_ideas_config
                    generate_keyword_historical_metrics_config = parent_rpcs.generate_keyword_historical_metrics if parent_rpcs.respond_to? :generate_keyword_historical_metrics
                    @generate_keyword_historical_metrics = ::Gapic::Config::Method.new generate_keyword_historical_metrics_config
                    generate_ad_group_themes_config = parent_rpcs.generate_ad_group_themes if parent_rpcs.respond_to? :generate_ad_group_themes
                    @generate_ad_group_themes = ::Gapic::Config::Method.new generate_ad_group_themes_config
                    generate_keyword_forecast_metrics_config = parent_rpcs.generate_keyword_forecast_metrics if parent_rpcs.respond_to? :generate_keyword_forecast_metrics
                    @generate_keyword_forecast_metrics = ::Gapic::Config::Method.new generate_keyword_forecast_metrics_config

                    yield self if block_given?
                  end
                end
              end
            end
          end
        end
      end
    end
  end
end
