# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v21/errors/asset_set_error.proto

require 'google/protobuf'


descriptor_data = "\n5google/ads/googleads/v21/errors/asset_set_error.proto\x12\x1fgoogle.ads.googleads.v21.errors\"\xef\x03\n\x11\x41ssetSetErrorEnum\"\xd9\x03\n\rAssetSetError\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x0b\n\x07UNKNOWN\x10\x01\x12\x1c\n\x18\x44UPLICATE_ASSET_SET_NAME\x10\x02\x12!\n\x1dINVALID_PARENT_ASSET_SET_TYPE\x10\x03\x12\x37\n3ASSET_SET_SOURCE_INCOMPATIBLE_WITH_PARENT_ASSET_SET\x10\x04\x12/\n+ASSET_SET_TYPE_CANNOT_BE_LINKED_TO_CUSTOMER\x10\x05\x12\x15\n\x11INVALID_CHAIN_IDS\x10\x06\x12>\n:LOCATION_SYNC_ASSET_SET_DOES_NOT_SUPPORT_RELATIONSHIP_TYPE\x10\x07\x12\x34\n0NOT_UNIQUE_ENABLED_LOCATION_SYNC_TYPED_ASSET_SET\x10\x08\x12\x15\n\x11INVALID_PLACE_IDS\x10\t\x12\x16\n\x12OAUTH_INFO_INVALID\x10\x0b\x12\x16\n\x12OAUTH_INFO_MISSING\x10\x0c\x12+\n\'CANNOT_DELETE_AS_ENABLED_LINKAGES_EXIST\x10\nB\xf2\x01\n#com.google.ads.googleads.v21.errorsB\x12\x41ssetSetErrorProtoP\x01ZEgoogle.golang.org/genproto/googleapis/ads/googleads/v21/errors;errors\xa2\x02\x03GAA\xaa\x02\x1fGoogle.Ads.GoogleAds.V21.Errors\xca\x02\x1fGoogle\\Ads\\GoogleAds\\V21\\Errors\xea\x02#Google::Ads::GoogleAds::V21::Errorsb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Google
  module Ads
    module GoogleAds
      module V21
        module Errors
          AssetSetErrorEnum = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v21.errors.AssetSetErrorEnum").msgclass
          AssetSetErrorEnum::AssetSetError = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v21.errors.AssetSetErrorEnum.AssetSetError").enummodule
        end
      end
    end
  end
end
