# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v21/errors/customer_customizer_error.proto

require 'google/protobuf'


descriptor_data = "\n?google/ads/googleads/v21/errors/customer_customizer_error.proto\x12\x1fgoogle.ads.googleads.v21.errors\"V\n\x1b\x43ustomerCustomizerErrorEnum\"7\n\x17\x43ustomerCustomizerError\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x0b\n\x07UNKNOWN\x10\x01\x42\xfc\x01\n#com.google.ads.googleads.v21.errorsB\x1c\x43ustomerCustomizerErrorProtoP\x01ZEgoogle.golang.org/genproto/googleapis/ads/googleads/v21/errors;errors\xa2\x02\x03GAA\xaa\x02\x1fGoogle.Ads.GoogleAds.V21.Errors\xca\x02\x1fGoogle\\Ads\\GoogleAds\\V21\\Errors\xea\x02#Google::Ads::GoogleAds::V21::Errorsb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Google
  module Ads
    module GoogleAds
      module V21
        module Errors
          CustomerCustomizerErrorEnum = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v21.errors.CustomerCustomizerErrorEnum").msgclass
          CustomerCustomizerErrorEnum::CustomerCustomizerError = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v21.errors.CustomerCustomizerErrorEnum.CustomerCustomizerError").enummodule
        end
      end
    end
  end
end
