# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v21/errors/new_resource_creation_error.proto

require 'google/protobuf'


descriptor_data = "\nAgoogle/ads/googleads/v21/errors/new_resource_creation_error.proto\x12\x1fgoogle.ads.googleads.v21.errors\"\xb0\x01\n\x1cNewResourceCreationErrorEnum\"\x8f\x01\n\x18NewResourceCreationError\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x0b\n\x07UNKNOWN\x10\x01\x12\x1c\n\x18\x43\x41NNOT_SET_ID_FOR_CREATE\x10\x02\x12\x16\n\x12\x44UPLICATE_TEMP_IDS\x10\x03\x12\x1f\n\x1bTEMP_ID_RESOURCE_HAD_ERRORS\x10\x04\x42\xfd\x01\n#com.google.ads.googleads.v21.errorsB\x1dNewResourceCreationErrorProtoP\x01ZEgoogle.golang.org/genproto/googleapis/ads/googleads/v21/errors;errors\xa2\x02\x03GAA\xaa\x02\x1fGoogle.Ads.GoogleAds.V21.Errors\xca\x02\x1fGoogle\\Ads\\GoogleAds\\V21\\Errors\xea\x02#Google::Ads::GoogleAds::V21::Errorsb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Google
  module Ads
    module GoogleAds
      module V21
        module Errors
          NewResourceCreationErrorEnum = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v21.errors.NewResourceCreationErrorEnum").msgclass
          NewResourceCreationErrorEnum::NewResourceCreationError = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v21.errors.NewResourceCreationErrorEnum.NewResourceCreationError").enummodule
        end
      end
    end
  end
end
