# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v25/enums/ad_sub_format_type.proto

require 'google/protobuf'


descriptor_data = "\n7google/ads/googleads/v25/enums/ad_sub_format_type.proto\x12\x1egoogle.ads.googleads.v25.enums\"\xc9\x01\n\x13\x41\x64SubFormatTypeEnum\"\xb1\x01\n\x0f\x41\x64SubFormatType\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x0b\n\x07UNKNOWN\x10\x01\x12\x0f\n\x0bUNSEGMENTED\x10\x02\x12#\n\x1fINSTREAM_NON_SKIPPABLE_STANDARD\x10\x03\x12$\n INSTREAM_NON_SKIPPABLE_MAX30_SEC\x10\x04\x12$\n INSTREAM_NON_SKIPPABLE_MAX60_SEC\x10\x05\x42\xee\x01\n\"com.google.ads.googleads.v25.enumsB\x14\x41\x64SubFormatTypeProtoP\x01ZCgoogle.golang.org/genproto/googleapis/ads/googleads/v25/enums;enums\xa2\x02\x03GAA\xaa\x02\x1eGoogle.Ads.GoogleAds.V25.Enums\xca\x02\x1eGoogle\\Ads\\GoogleAds\\V25\\Enums\xea\x02\"Google::Ads::GoogleAds::V25::Enumsb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Google
  module Ads
    module GoogleAds
      module V25
        module Enums
          AdSubFormatTypeEnum = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v25.enums.AdSubFormatTypeEnum").msgclass
          AdSubFormatTypeEnum::AdSubFormatType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v25.enums.AdSubFormatTypeEnum.AdSubFormatType").enummodule
        end
      end
    end
  end
end
