# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v23/resources/customer_lifecycle_goal.proto

require 'google/protobuf'

require 'google/ads/google_ads/v23/common/lifecycle_goals_pb'
require 'google/api/field_behavior_pb'
require 'google/api/resource_pb'


descriptor_data = "\n@google/ads/googleads/v23/resources/customer_lifecycle_goal.proto\x12\"google.ads.googleads.v23.resources\x1a\x35google/ads/googleads/v23/common/lifecycle_goals.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\"\x82\x03\n\x15\x43ustomerLifecycleGoal\x12M\n\rresource_name\x18\x01 \x01(\tB6\xe0\x41\x05\xfa\x41\x30\n.googleads.googleapis.com/CustomerLifecycleGoal\x12r\n(customer_acquisition_goal_value_settings\x18\x03 \x01(\x0b\x32;.google.ads.googleads.v23.common.LifecycleGoalValueSettingsB\x03\xe0\x41\x03\x12\x41\n\x0eowner_customer\x18\x04 \x01(\tB)\xe0\x41\x03\xfa\x41#\n!googleads.googleapis.com/Customer:c\xea\x41`\n.googleads.googleapis.com/CustomerLifecycleGoal\x12.customers/{customer_id}/customerLifecycleGoalsB\x8c\x02\n&com.google.ads.googleads.v23.resourcesB\x1a\x43ustomerLifecycleGoalProtoP\x01ZKgoogle.golang.org/genproto/googleapis/ads/googleads/v23/resources;resources\xa2\x02\x03GAA\xaa\x02\"Google.Ads.GoogleAds.V23.Resources\xca\x02\"Google\\Ads\\GoogleAds\\V23\\Resources\xea\x02&Google::Ads::GoogleAds::V23::Resourcesb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Google
  module Ads
    module GoogleAds
      module V23
        module Resources
          CustomerLifecycleGoal = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v23.resources.CustomerLifecycleGoal").msgclass
        end
      end
    end
  end
end
