# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v24/resources/app_top_combination_view.proto

require 'google/protobuf'

require 'google/ads/google_ads/v24/common/asset_usage_pb'
require 'google/api/field_behavior_pb'
require 'google/api/resource_pb'


descriptor_data = "\nAgoogle/ads/googleads/v24/resources/app_top_combination_view.proto\x12\"google.ads.googleads.v24.resources\x1a\x31google/ads/googleads/v24/common/asset_usage.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\"\xa0\x03\n\x15\x41ppTopCombinationView\x12M\n\rresource_name\x18\x01 \x01(\tB6\xe0\x41\x03\xfa\x41\x30\n.googleads.googleapis.com/AppTopCombinationView\x12o\n\x19\x61\x64_group_top_combinations\x18\x02 \x03(\x0b\x32G.google.ads.googleads.v24.resources.AdGroupCreativeAssetCombinationDataB\x03\xe0\x41\x03:\xc6\x01\xea\x41\xc2\x01\n.googleads.googleapis.com/AppTopCombinationView\x12\x61\x63ustomers/{customer_id}/appTopCombinationViews/{ad_group_id}~{ad_id}~{asset_combination_category}*\x16\x61ppTopCombinationViews2\x15\x61ppTopCombinationView\"\x80\x01\n#AdGroupCreativeAssetCombinationData\x12Y\n\x1f\x61sset_combination_served_assets\x18\x01 \x03(\x0b\x32+.google.ads.googleads.v24.common.AssetUsageB\x03\xe0\x41\x03\x42\x8c\x02\n&com.google.ads.googleads.v24.resourcesB\x1a\x41ppTopCombinationViewProtoP\x01ZKgoogle.golang.org/genproto/googleapis/ads/googleads/v24/resources;resources\xa2\x02\x03GAA\xaa\x02\"Google.Ads.GoogleAds.V24.Resources\xca\x02\"Google\\Ads\\GoogleAds\\V24\\Resources\xea\x02&Google::Ads::GoogleAds::V24::Resourcesb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Google
  module Ads
    module GoogleAds
      module V24
        module Resources
          AppTopCombinationView = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v24.resources.AppTopCombinationView").msgclass
          AdGroupCreativeAssetCombinationData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v24.resources.AdGroupCreativeAssetCombinationData").msgclass
        end
      end
    end
  end
end
