# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v24/resources/qualifying_question.proto

require 'google/protobuf'

require 'google/api/field_behavior_pb'
require 'google/api/resource_pb'


descriptor_data = "\n<google/ads/googleads/v24/resources/qualifying_question.proto\x12\"google.ads.googleads.v24.resources\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\"\x8d\x02\n\x12QualifyingQuestion\x12J\n\rresource_name\x18\x01 \x01(\tB3\xe0\x41\x03\xfa\x41-\n+googleads.googleapis.com/QualifyingQuestion\x12#\n\x16qualifying_question_id\x18\x02 \x01(\x03\x42\x03\xe0\x41\x03\x12\x13\n\x06locale\x18\x03 \x01(\tB\x03\xe0\x41\x03\x12\x11\n\x04text\x18\x04 \x01(\tB\x03\xe0\x41\x03:^\xea\x41[\n+googleads.googleapis.com/QualifyingQuestion\x12,qualifyingQuestions/{qualifying_question_id}B\x89\x02\n&com.google.ads.googleads.v24.resourcesB\x17QualifyingQuestionProtoP\x01ZKgoogle.golang.org/genproto/googleapis/ads/googleads/v24/resources;resources\xa2\x02\x03GAA\xaa\x02\"Google.Ads.GoogleAds.V24.Resources\xca\x02\"Google\\Ads\\GoogleAds\\V24\\Resources\xea\x02&Google::Ads::GoogleAds::V24::Resourcesb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Google
  module Ads
    module GoogleAds
      module V24
        module Resources
          QualifyingQuestion = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v24.resources.QualifyingQuestion").msgclass
        end
      end
    end
  end
end
