# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v9/resources/user_location_view.proto

require 'google/api/field_behavior_pb'
require 'google/api/resource_pb'
require 'google/api/annotations_pb'
require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/ads/googleads/v9/resources/user_location_view.proto", :syntax => :proto3) do
    add_message "google.ads.googleads.v9.resources.UserLocationView" do
      optional :resource_name, :string, 1
      proto3_optional :country_criterion_id, :int64, 4
      proto3_optional :targeting_location, :bool, 5
    end
  end
end

module Google
  module Ads
    module GoogleAds
      module V9
        module Resources
          UserLocationView = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v9.resources.UserLocationView").msgclass
        end
      end
    end
  end
end
