# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v22/services/custom_interest_service.proto

require 'google/protobuf'

require 'google/ads/google_ads/v22/resources/custom_interest_pb'
require 'google/api/annotations_pb'
require 'google/api/client_pb'
require 'google/api/field_behavior_pb'
require 'google/api/resource_pb'
require 'google/protobuf/field_mask_pb'


descriptor_data = "\n?google/ads/googleads/v22/services/custom_interest_service.proto\x12!google.ads.googleads.v22.services\x1a\x38google/ads/googleads/v22/resources/custom_interest.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a google/protobuf/field_mask.proto\"\xa4\x01\n\x1cMutateCustomInterestsRequest\x12\x18\n\x0b\x63ustomer_id\x18\x01 \x01(\tB\x03\xe0\x41\x02\x12S\n\noperations\x18\x02 \x03(\x0b\x32:.google.ads.googleads.v22.services.CustomInterestOperationB\x03\xe0\x41\x02\x12\x15\n\rvalidate_only\x18\x04 \x01(\x08\"\xe3\x01\n\x17\x43ustomInterestOperation\x12/\n\x0bupdate_mask\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.FieldMask\x12\x44\n\x06\x63reate\x18\x01 \x01(\x0b\x32\x32.google.ads.googleads.v22.resources.CustomInterestH\x00\x12\x44\n\x06update\x18\x02 \x01(\x0b\x32\x32.google.ads.googleads.v22.resources.CustomInterestH\x00\x42\x0b\n\toperation\"o\n\x1dMutateCustomInterestsResponse\x12N\n\x07results\x18\x02 \x03(\x0b\x32=.google.ads.googleads.v22.services.MutateCustomInterestResult\"a\n\x1aMutateCustomInterestResult\x12\x43\n\rresource_name\x18\x01 \x01(\tB,\xfa\x41)\n\'googleads.googleapis.com/CustomInterest2\xd6\x02\n\x15\x43ustomInterestService\x12\xf5\x01\n\x15MutateCustomInterests\x12?.google.ads.googleads.v22.services.MutateCustomInterestsRequest\x1a@.google.ads.googleads.v22.services.MutateCustomInterestsResponse\"Y\xda\x41\x16\x63ustomer_id,operations\x82\xd3\xe4\x93\x02:\"5/v22/customers/{customer_id=*}/customInterests:mutate:\x01*\x1a\x45\xca\x41\x18googleads.googleapis.com\xd2\x41\'https://www.googleapis.com/auth/adwordsB\x86\x02\n%com.google.ads.googleads.v22.servicesB\x1a\x43ustomInterestServiceProtoP\x01ZIgoogle.golang.org/genproto/googleapis/ads/googleads/v22/services;services\xa2\x02\x03GAA\xaa\x02!Google.Ads.GoogleAds.V22.Services\xca\x02!Google\\Ads\\GoogleAds\\V22\\Services\xea\x02%Google::Ads::GoogleAds::V22::Servicesb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
    ["google.protobuf.FieldMask", "google/protobuf/field_mask.proto"],
    ["google.ads.googleads.v22.resources.CustomInterest", "google/ads/googleads/v22/resources/custom_interest.proto"],
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Google
  module Ads
    module GoogleAds
      module V22
        module Services
          MutateCustomInterestsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v22.services.MutateCustomInterestsRequest").msgclass
          CustomInterestOperation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v22.services.CustomInterestOperation").msgclass
          MutateCustomInterestsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v22.services.MutateCustomInterestsResponse").msgclass
          MutateCustomInterestResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v22.services.MutateCustomInterestResult").msgclass
        end
      end
    end
  end
end
