# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v22/services/google_ads_field_service.proto

require 'google/protobuf'

require 'google/ads/google_ads/v22/resources/google_ads_field_pb'
require 'google/api/annotations_pb'
require 'google/api/client_pb'
require 'google/api/field_behavior_pb'
require 'google/api/resource_pb'


descriptor_data = "\n@google/ads/googleads/v22/services/google_ads_field_service.proto\x12!google.ads.googleads.v22.services\x1a\x39google/ads/googleads/v22/resources/google_ads_field.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\"b\n\x18GetGoogleAdsFieldRequest\x12\x46\n\rresource_name\x18\x01 \x01(\tB/\xe0\x41\x02\xfa\x41)\n\'googleads.googleapis.com/GoogleAdsField\"Y\n\x1cSearchGoogleAdsFieldsRequest\x12\x12\n\x05query\x18\x01 \x01(\tB\x03\xe0\x41\x02\x12\x12\n\npage_token\x18\x02 \x01(\t\x12\x11\n\tpage_size\x18\x03 \x01(\x05\"\x9a\x01\n\x1dSearchGoogleAdsFieldsResponse\x12\x43\n\x07results\x18\x01 \x03(\x0b\x32\x32.google.ads.googleads.v22.resources.GoogleAdsField\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x1b\n\x13total_results_count\x18\x03 \x01(\x03\x32\xf2\x03\n\x15GoogleAdsFieldService\x12\xc4\x01\n\x11GetGoogleAdsField\x12;.google.ads.googleads.v22.services.GetGoogleAdsFieldRequest\x1a\x32.google.ads.googleads.v22.resources.GoogleAdsField\">\xda\x41\rresource_name\x82\xd3\xe4\x93\x02(\x12&/v22/{resource_name=googleAdsFields/*}\x12\xca\x01\n\x15SearchGoogleAdsFields\x12?.google.ads.googleads.v22.services.SearchGoogleAdsFieldsRequest\x1a@.google.ads.googleads.v22.services.SearchGoogleAdsFieldsResponse\".\xda\x41\x05query\x82\xd3\xe4\x93\x02 \"\x1b/v22/googleAdsFields:search:\x01*\x1a\x45\xca\x41\x18googleads.googleapis.com\xd2\x41\'https://www.googleapis.com/auth/adwordsB\x86\x02\n%com.google.ads.googleads.v22.servicesB\x1aGoogleAdsFieldServiceProtoP\x01ZIgoogle.golang.org/genproto/googleapis/ads/googleads/v22/services;services\xa2\x02\x03GAA\xaa\x02!Google.Ads.GoogleAds.V22.Services\xca\x02!Google\\Ads\\GoogleAds\\V22\\Services\xea\x02%Google::Ads::GoogleAds::V22::Servicesb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Google
  module Ads
    module GoogleAds
      module V22
        module Services
          GetGoogleAdsFieldRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v22.services.GetGoogleAdsFieldRequest").msgclass
          SearchGoogleAdsFieldsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v22.services.SearchGoogleAdsFieldsRequest").msgclass
          SearchGoogleAdsFieldsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v22.services.SearchGoogleAdsFieldsResponse").msgclass
        end
      end
    end
  end
end
