# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v22/services/keyword_theme_constant_service.proto

require 'google/protobuf'

require 'google/ads/google_ads/v22/resources/keyword_theme_constant_pb'
require 'google/api/annotations_pb'
require 'google/api/client_pb'


descriptor_data = "\nFgoogle/ads/googleads/v22/services/keyword_theme_constant_service.proto\x12!google.ads.googleads.v22.services\x1a?google/ads/googleads/v22/resources/keyword_theme_constant.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\"f\n#SuggestKeywordThemeConstantsRequest\x12\x12\n\nquery_text\x18\x01 \x01(\t\x12\x14\n\x0c\x63ountry_code\x18\x02 \x01(\t\x12\x15\n\rlanguage_code\x18\x03 \x01(\t\"\x81\x01\n$SuggestKeywordThemeConstantsResponse\x12Y\n\x17keyword_theme_constants\x18\x01 \x03(\x0b\x32\x38.google.ads.googleads.v22.resources.KeywordThemeConstant2\xc5\x02\n\x1bKeywordThemeConstantService\x12\xde\x01\n\x1cSuggestKeywordThemeConstants\x12\x46.google.ads.googleads.v22.services.SuggestKeywordThemeConstantsRequest\x1aG.google.ads.googleads.v22.services.SuggestKeywordThemeConstantsResponse\"-\x82\xd3\xe4\x93\x02\'\"\"/v22/keywordThemeConstants:suggest:\x01*\x1a\x45\xca\x41\x18googleads.googleapis.com\xd2\x41\'https://www.googleapis.com/auth/adwordsB\x8c\x02\n%com.google.ads.googleads.v22.servicesB KeywordThemeConstantServiceProtoP\x01ZIgoogle.golang.org/genproto/googleapis/ads/googleads/v22/services;services\xa2\x02\x03GAA\xaa\x02!Google.Ads.GoogleAds.V22.Services\xca\x02!Google\\Ads\\GoogleAds\\V22\\Services\xea\x02%Google::Ads::GoogleAds::V22::Servicesb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Google
  module Ads
    module GoogleAds
      module V22
        module Services
          SuggestKeywordThemeConstantsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v22.services.SuggestKeywordThemeConstantsRequest").msgclass
          SuggestKeywordThemeConstantsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v22.services.SuggestKeywordThemeConstantsResponse").msgclass
        end
      end
    end
  end
end
