# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v23/common/campaign_goal_settings.proto

require 'google/protobuf'

require 'google/ads/google_ads/v23/common/goal_common_pb'
require 'google/ads/google_ads/v23/enums/customer_lifecycle_optimization_mode_pb'


descriptor_data = "\n<google/ads/googleads/v23/common/campaign_goal_settings.proto\x12\x1fgoogle.ads.googleads.v23.common\x1a\x31google/ads/googleads/v23/common/goal_common.proto\x1aIgoogle/ads/googleads/v23/enums/customer_lifecycle_optimization_mode.proto\"\xa6\x02\n\x14\x43\x61mpaignGoalSettings\x1a\x8d\x02\n\x1d\x43\x61mpaignRetentionGoalSettings\x12l\n\x17value_settings_override\x18\x01 \x01(\x0b\x32K.google.ads.googleads.v23.common.CustomerLifecycleOptimizationValueSettings\x12~\n\rtarget_option\x18\x02 \x01(\x0e\x32g.google.ads.googleads.v23.enums.CustomerLifecycleOptimizationModeEnum.CustomerLifecycleOptimizationModeB\xf9\x01\n#com.google.ads.googleads.v23.commonB\x19\x43\x61mpaignGoalSettingsProtoP\x01ZEgoogle.golang.org/genproto/googleapis/ads/googleads/v23/common;common\xa2\x02\x03GAA\xaa\x02\x1fGoogle.Ads.GoogleAds.V23.Common\xca\x02\x1fGoogle\\Ads\\GoogleAds\\V23\\Common\xea\x02#Google::Ads::GoogleAds::V23::Commonb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Google
  module Ads
    module GoogleAds
      module V23
        module Common
          CampaignGoalSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v23.common.CampaignGoalSettings").msgclass
          CampaignGoalSettings::CampaignRetentionGoalSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v23.common.CampaignGoalSettings.CampaignRetentionGoalSettings").msgclass
        end
      end
    end
  end
end
