# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v13/resources/smart_campaign_search_term_view.proto

require 'google/protobuf'

require 'google/api/field_behavior_pb'
require 'google/api/resource_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/ads/googleads/v13/resources/smart_campaign_search_term_view.proto", :syntax => :proto3) do
    add_message "google.ads.googleads.v13.resources.SmartCampaignSearchTermView" do
      optional :resource_name, :string, 1
      optional :search_term, :string, 2
      optional :campaign, :string, 3
    end
  end
end

module Google
  module Ads
    module GoogleAds
      module V13
        module Resources
          SmartCampaignSearchTermView = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v13.resources.SmartCampaignSearchTermView").msgclass
        end
      end
    end
  end
end
