# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v25/errors/time_zone_error.proto

require 'google/protobuf'


descriptor_data = "\n5google/ads/googleads/v25/errors/time_zone_error.proto\x12\x1fgoogle.ads.googleads.v25.errors\"Y\n\x11TimeZoneErrorEnum\"D\n\rTimeZoneError\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x0b\n\x07UNKNOWN\x10\x01\x12\x15\n\x11INVALID_TIME_ZONE\x10\x05\x42\xf2\x01\n#com.google.ads.googleads.v25.errorsB\x12TimeZoneErrorProtoP\x01ZEgoogle.golang.org/genproto/googleapis/ads/googleads/v25/errors;errors\xa2\x02\x03GAA\xaa\x02\x1fGoogle.Ads.GoogleAds.V25.Errors\xca\x02\x1fGoogle\\Ads\\GoogleAds\\V25\\Errors\xea\x02#Google::Ads::GoogleAds::V25::Errorsb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Google
  module Ads
    module GoogleAds
      module V25
        module Errors
          TimeZoneErrorEnum = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v25.errors.TimeZoneErrorEnum").msgclass
          TimeZoneErrorEnum::TimeZoneError = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v25.errors.TimeZoneErrorEnum.TimeZoneError").enummodule
        end
      end
    end
  end
end
