# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v21/resources/asset_group_product_group_view.proto

require 'google/protobuf'

require 'google/api/field_behavior_pb'
require 'google/api/resource_pb'


descriptor_data = "\nGgoogle/ads/googleads/v21/resources/asset_group_product_group_view.proto\x12\"google.ads.googleads.v21.resources\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\"\xb7\x03\n\x1a\x41ssetGroupProductGroupView\x12R\n\rresource_name\x18\x01 \x01(\tB;\xe0\x41\x03\xfa\x41\x35\n3googleads.googleapis.com/AssetGroupProductGroupView\x12@\n\x0b\x61sset_group\x18\x02 \x01(\tB+\xe0\x41\x03\xfa\x41%\n#googleads.googleapis.com/AssetGroup\x12g\n asset_group_listing_group_filter\x18\x04 \x01(\tB=\xe0\x41\x03\xfa\x41\x37\n5googleads.googleapis.com/AssetGroupListingGroupFilter:\x99\x01\xea\x41\x95\x01\n3googleads.googleapis.com/AssetGroupProductGroupView\x12^customers/{customer_id}/assetGroupProductGroupViews/{asset_group_id}~{listing_group_filter_id}B\x91\x02\n&com.google.ads.googleads.v21.resourcesB\x1f\x41ssetGroupProductGroupViewProtoP\x01ZKgoogle.golang.org/genproto/googleapis/ads/googleads/v21/resources;resources\xa2\x02\x03GAA\xaa\x02\"Google.Ads.GoogleAds.V21.Resources\xca\x02\"Google\\Ads\\GoogleAds\\V21\\Resources\xea\x02&Google::Ads::GoogleAds::V21::Resourcesb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Google
  module Ads
    module GoogleAds
      module V21
        module Resources
          AssetGroupProductGroupView = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v21.resources.AssetGroupProductGroupView").msgclass
        end
      end
    end
  end
end
