# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v21/resources/asset_set_asset.proto

require 'google/protobuf'

require 'google/ads/google_ads/v21/enums/asset_set_asset_status_pb'
require 'google/api/field_behavior_pb'
require 'google/api/resource_pb'


descriptor_data = "\n8google/ads/googleads/v21/resources/asset_set_asset.proto\x12\"google.ads.googleads.v21.resources\x1a;google/ads/googleads/v21/enums/asset_set_asset_status.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\"\x9c\x03\n\rAssetSetAsset\x12\x45\n\rresource_name\x18\x01 \x01(\tB.\xe0\x41\x05\xfa\x41(\n&googleads.googleapis.com/AssetSetAsset\x12<\n\tasset_set\x18\x02 \x01(\tB)\xe0\x41\x05\xfa\x41#\n!googleads.googleapis.com/AssetSet\x12\x35\n\x05\x61sset\x18\x03 \x01(\tB&\xe0\x41\x05\xfa\x41 \n\x1egoogleads.googleapis.com/Asset\x12`\n\x06status\x18\x04 \x01(\x0e\x32K.google.ads.googleads.v21.enums.AssetSetAssetStatusEnum.AssetSetAssetStatusB\x03\xe0\x41\x03:m\xea\x41j\n&googleads.googleapis.com/AssetSetAsset\x12@customers/{customer_id}/assetSetAssets/{asset_set_id}~{asset_id}B\x84\x02\n&com.google.ads.googleads.v21.resourcesB\x12\x41ssetSetAssetProtoP\x01ZKgoogle.golang.org/genproto/googleapis/ads/googleads/v21/resources;resources\xa2\x02\x03GAA\xaa\x02\"Google.Ads.GoogleAds.V21.Resources\xca\x02\"Google\\Ads\\GoogleAds\\V21\\Resources\xea\x02&Google::Ads::GoogleAds::V21::Resourcesb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Google
  module Ads
    module GoogleAds
      module V21
        module Resources
          AssetSetAsset = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v21.resources.AssetSetAsset").msgclass
        end
      end
    end
  end
end
