# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v21/resources/detail_content_suitability_placement_view.proto

require 'google/protobuf'

require 'google/ads/google_ads/v21/enums/placement_type_pb'
require 'google/api/field_behavior_pb'
require 'google/api/resource_pb'


descriptor_data = "\nRgoogle/ads/googleads/v21/resources/detail_content_suitability_placement_view.proto\x12\"google.ads.googleads.v21.resources\x1a\x33google/ads/googleads/v21/enums/placement_type.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\"\x9e\x04\n%DetailContentSuitabilityPlacementView\x12]\n\rresource_name\x18\x01 \x01(\tBF\xe0\x41\x03\xfa\x41@\n>googleads.googleapis.com/DetailContentSuitabilityPlacementView\x12\x19\n\x0c\x64isplay_name\x18\x02 \x01(\tB\x03\xe0\x41\x03\x12\x16\n\tplacement\x18\x03 \x01(\tB\x03\xe0\x41\x03\x12\\\n\x0eplacement_type\x18\x04 \x01(\x0e\x32?.google.ads.googleads.v21.enums.PlacementTypeEnum.PlacementTypeB\x03\xe0\x41\x03\x12\x17\n\ntarget_url\x18\x05 \x01(\tB\x03\xe0\x41\x03:\xeb\x01\xea\x41\xe7\x01\n>googleads.googleapis.com/DetailContentSuitabilityPlacementView\x12Vcustomers/{customer_id}/detailContentSuitabilityPlacementViews/{placement_fingerprint}*&detailContentSuitabilityPlacementViews2%detailContentSuitabilityPlacementViewB\x9c\x02\n&com.google.ads.googleads.v21.resourcesB*DetailContentSuitabilityPlacementViewProtoP\x01ZKgoogle.golang.org/genproto/googleapis/ads/googleads/v21/resources;resources\xa2\x02\x03GAA\xaa\x02\"Google.Ads.GoogleAds.V21.Resources\xca\x02\"Google\\Ads\\GoogleAds\\V21\\Resources\xea\x02&Google::Ads::GoogleAds::V21::Resourcesb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Google
  module Ads
    module GoogleAds
      module V21
        module Resources
          DetailContentSuitabilityPlacementView = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v21.resources.DetailContentSuitabilityPlacementView").msgclass
        end
      end
    end
  end
end
