#!/bin/bash
set -euxo pipefail

export VERSIONS="v1 v2 v3"
export WORKDIR=$(mktemp -d /tmp/ruby-gapic-XXXXXXXXXX)

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source "${SCRIPT_DIR}/functions.sh"

copy_protos_from_googleapis "${WORKDIR}"
build_and_commit_protos "${WORKDIR}" "$(pwd)"
