# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/google_ads/v0/common/policy.proto

require 'google/protobuf'

require 'google/ads/google_ads/v0/enums/policy_topic_entry_type_pb'
require 'google/ads/google_ads/v0/enums/policy_topic_evidence_destination_mismatch_url_type_pb'
require 'google/protobuf/wrappers_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "google.ads.googleads.v0.common.PolicyViolationKey" do
    optional :policy_name, :message, 1, "google.protobuf.StringValue"
    optional :violating_text, :message, 2, "google.protobuf.StringValue"
  end
  add_message "google.ads.googleads.v0.common.PolicyValidationParameter" do
    repeated :ignorable_policy_topics, :message, 1, "google.protobuf.StringValue"
  end
  add_message "google.ads.googleads.v0.common.PolicyTopicEntry" do
    optional :topic, :message, 1, "google.protobuf.StringValue"
    optional :type, :enum, 2, "google.ads.googleads.v0.enums.PolicyTopicEntryTypeEnum.PolicyTopicEntryType"
    repeated :evidences, :message, 3, "google.ads.googleads.v0.common.PolicyTopicEvidence"
    repeated :constraints, :message, 4, "google.ads.googleads.v0.common.PolicyTopicConstraint"
  end
  add_message "google.ads.googleads.v0.common.PolicyTopicEvidence" do
    oneof :value do
      optional :http_code, :message, 2, "google.protobuf.Int32Value"
      optional :website_list, :message, 3, "google.ads.googleads.v0.common.PolicyTopicEvidence.WebsiteList"
      optional :text_list, :message, 4, "google.ads.googleads.v0.common.PolicyTopicEvidence.TextList"
      optional :language_code, :message, 5, "google.protobuf.StringValue"
      optional :destination_text_list, :message, 6, "google.ads.googleads.v0.common.PolicyTopicEvidence.DestinationTextList"
      optional :destination_mismatch, :message, 7, "google.ads.googleads.v0.common.PolicyTopicEvidence.DestinationMismatch"
    end
  end
  add_message "google.ads.googleads.v0.common.PolicyTopicEvidence.TextList" do
    repeated :texts, :message, 1, "google.protobuf.StringValue"
  end
  add_message "google.ads.googleads.v0.common.PolicyTopicEvidence.WebsiteList" do
    repeated :websites, :message, 1, "google.protobuf.StringValue"
  end
  add_message "google.ads.googleads.v0.common.PolicyTopicEvidence.DestinationTextList" do
    repeated :destination_texts, :message, 1, "google.protobuf.StringValue"
  end
  add_message "google.ads.googleads.v0.common.PolicyTopicEvidence.DestinationMismatch" do
    repeated :url_types, :enum, 1, "google.ads.googleads.v0.enums.PolicyTopicEvidenceDestinationMismatchUrlTypeEnum.PolicyTopicEvidenceDestinationMismatchUrlType"
  end
  add_message "google.ads.googleads.v0.common.PolicyTopicConstraint" do
    oneof :value do
      optional :country_constraint_list, :message, 1, "google.ads.googleads.v0.common.PolicyTopicConstraint.CountryConstraintList"
      optional :reseller_constraint, :message, 2, "google.ads.googleads.v0.common.PolicyTopicConstraint.ResellerConstraint"
      optional :certificate_missing_in_country_list, :message, 3, "google.ads.googleads.v0.common.PolicyTopicConstraint.CountryConstraintList"
      optional :certificate_domain_mismatch_in_country_list, :message, 4, "google.ads.googleads.v0.common.PolicyTopicConstraint.CountryConstraintList"
    end
  end
  add_message "google.ads.googleads.v0.common.PolicyTopicConstraint.CountryConstraintList" do
    optional :total_targeted_countries, :message, 1, "google.protobuf.Int32Value"
    repeated :countries, :message, 2, "google.ads.googleads.v0.common.PolicyTopicConstraint.CountryConstraint"
  end
  add_message "google.ads.googleads.v0.common.PolicyTopicConstraint.ResellerConstraint" do
  end
  add_message "google.ads.googleads.v0.common.PolicyTopicConstraint.CountryConstraint" do
    optional :country_criterion, :message, 1, "google.protobuf.StringValue"
  end
end

module Google
  module Ads
    module GoogleAds
      module V0
        module Common
          PolicyViolationKey = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v0.common.PolicyViolationKey").msgclass
          PolicyValidationParameter = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v0.common.PolicyValidationParameter").msgclass
          PolicyTopicEntry = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v0.common.PolicyTopicEntry").msgclass
          PolicyTopicEvidence = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v0.common.PolicyTopicEvidence").msgclass
          PolicyTopicEvidence::TextList = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v0.common.PolicyTopicEvidence.TextList").msgclass
          PolicyTopicEvidence::WebsiteList = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v0.common.PolicyTopicEvidence.WebsiteList").msgclass
          PolicyTopicEvidence::DestinationTextList = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v0.common.PolicyTopicEvidence.DestinationTextList").msgclass
          PolicyTopicEvidence::DestinationMismatch = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v0.common.PolicyTopicEvidence.DestinationMismatch").msgclass
          PolicyTopicConstraint = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v0.common.PolicyTopicConstraint").msgclass
          PolicyTopicConstraint::CountryConstraintList = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v0.common.PolicyTopicConstraint.CountryConstraintList").msgclass
          PolicyTopicConstraint::ResellerConstraint = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v0.common.PolicyTopicConstraint.ResellerConstraint").msgclass
          PolicyTopicConstraint::CountryConstraint = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v0.common.PolicyTopicConstraint.CountryConstraint").msgclass
        end
      end
    end
  end
end
