# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v5/enums/product_channel_exclusivity.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/ads/googleads/v5/enums/product_channel_exclusivity.proto", :syntax => :proto3) do
    add_message "google.ads.googleads.v5.enums.ProductChannelExclusivityEnum" do
    end
    add_enum "google.ads.googleads.v5.enums.ProductChannelExclusivityEnum.ProductChannelExclusivity" do
      value :UNSPECIFIED, 0
      value :UNKNOWN, 1
      value :SINGLE_CHANNEL, 2
      value :MULTI_CHANNEL, 3
    end
  end
end

module Google
  module Ads
    module GoogleAds
      module V5
        module Enums
          ProductChannelExclusivityEnum = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v5.enums.ProductChannelExclusivityEnum").msgclass
          ProductChannelExclusivityEnum::ProductChannelExclusivity = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v5.enums.ProductChannelExclusivityEnum.ProductChannelExclusivity").enummodule
        end
      end
    end
  end
end
