# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v12/common/keyword_plan_common.proto

require 'google/protobuf'

require 'google/ads/google_ads/v12/common/dates_pb'
require 'google/ads/google_ads/v12/enums/device_pb'
require 'google/ads/google_ads/v12/enums/keyword_plan_aggregate_metric_type_pb'
require 'google/ads/google_ads/v12/enums/keyword_plan_competition_level_pb'
require 'google/ads/google_ads/v12/enums/keyword_plan_concept_group_type_pb'
require 'google/ads/google_ads/v12/enums/month_of_year_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/ads/googleads/v12/common/keyword_plan_common.proto", :syntax => :proto3) do
    add_message "google.ads.googleads.v12.common.KeywordPlanHistoricalMetrics" do
      proto3_optional :avg_monthly_searches, :int64, 7
      repeated :monthly_search_volumes, :message, 6, "google.ads.googleads.v12.common.MonthlySearchVolume"
      optional :competition, :enum, 2, "google.ads.googleads.v12.enums.KeywordPlanCompetitionLevelEnum.KeywordPlanCompetitionLevel"
      proto3_optional :competition_index, :int64, 8
      proto3_optional :low_top_of_page_bid_micros, :int64, 9
      proto3_optional :high_top_of_page_bid_micros, :int64, 10
      proto3_optional :average_cpc_micros, :int64, 11
    end
    add_message "google.ads.googleads.v12.common.HistoricalMetricsOptions" do
      proto3_optional :year_month_range, :message, 1, "google.ads.googleads.v12.common.YearMonthRange"
      optional :include_average_cpc, :bool, 2
    end
    add_message "google.ads.googleads.v12.common.MonthlySearchVolume" do
      proto3_optional :year, :int64, 4
      optional :month, :enum, 2, "google.ads.googleads.v12.enums.MonthOfYearEnum.MonthOfYear"
      proto3_optional :monthly_searches, :int64, 5
    end
    add_message "google.ads.googleads.v12.common.KeywordPlanAggregateMetrics" do
      repeated :aggregate_metric_types, :enum, 1, "google.ads.googleads.v12.enums.KeywordPlanAggregateMetricTypeEnum.KeywordPlanAggregateMetricType"
    end
    add_message "google.ads.googleads.v12.common.KeywordPlanAggregateMetricResults" do
      repeated :device_searches, :message, 1, "google.ads.googleads.v12.common.KeywordPlanDeviceSearches"
    end
    add_message "google.ads.googleads.v12.common.KeywordPlanDeviceSearches" do
      optional :device, :enum, 1, "google.ads.googleads.v12.enums.DeviceEnum.Device"
      proto3_optional :search_count, :int64, 2
    end
    add_message "google.ads.googleads.v12.common.KeywordAnnotations" do
      repeated :concepts, :message, 1, "google.ads.googleads.v12.common.KeywordConcept"
    end
    add_message "google.ads.googleads.v12.common.KeywordConcept" do
      optional :name, :string, 1
      optional :concept_group, :message, 2, "google.ads.googleads.v12.common.ConceptGroup"
    end
    add_message "google.ads.googleads.v12.common.ConceptGroup" do
      optional :name, :string, 1
      optional :type, :enum, 2, "google.ads.googleads.v12.enums.KeywordPlanConceptGroupTypeEnum.KeywordPlanConceptGroupType"
    end
  end
end

module Google
  module Ads
    module GoogleAds
      module V12
        module Common
          KeywordPlanHistoricalMetrics = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v12.common.KeywordPlanHistoricalMetrics").msgclass
          HistoricalMetricsOptions = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v12.common.HistoricalMetricsOptions").msgclass
          MonthlySearchVolume = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v12.common.MonthlySearchVolume").msgclass
          KeywordPlanAggregateMetrics = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v12.common.KeywordPlanAggregateMetrics").msgclass
          KeywordPlanAggregateMetricResults = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v12.common.KeywordPlanAggregateMetricResults").msgclass
          KeywordPlanDeviceSearches = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v12.common.KeywordPlanDeviceSearches").msgclass
          KeywordAnnotations = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v12.common.KeywordAnnotations").msgclass
          KeywordConcept = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v12.common.KeywordConcept").msgclass
          ConceptGroup = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v12.common.ConceptGroup").msgclass
        end
      end
    end
  end
end
