# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/google_ads/v4/enums/keyword_plan_network.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "google.ads.googleads.v4.enums.KeywordPlanNetworkEnum" do
  end
  add_enum "google.ads.googleads.v4.enums.KeywordPlanNetworkEnum.KeywordPlanNetwork" do
    value :UNSPECIFIED, 0
    value :UNKNOWN, 1
    value :GOOGLE_SEARCH, 2
    value :GOOGLE_SEARCH_AND_PARTNERS, 3
  end
end

module Google::Ads::GoogleAds::V4::Enums
  KeywordPlanNetworkEnum = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v4.enums.KeywordPlanNetworkEnum").msgclass
  KeywordPlanNetworkEnum::KeywordPlanNetwork = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v4.enums.KeywordPlanNetworkEnum.KeywordPlanNetwork").enummodule
end
