# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/google_ads/v4/enums/webpage_condition_operand.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "google.ads.googleads.v4.enums.WebpageConditionOperandEnum" do
  end
  add_enum "google.ads.googleads.v4.enums.WebpageConditionOperandEnum.WebpageConditionOperand" do
    value :UNSPECIFIED, 0
    value :UNKNOWN, 1
    value :URL, 2
    value :CATEGORY, 3
    value :PAGE_TITLE, 4
    value :PAGE_CONTENT, 5
    value :CUSTOM_LABEL, 6
  end
end

module Google::Ads::GoogleAds::V4::Enums
  WebpageConditionOperandEnum = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v4.enums.WebpageConditionOperandEnum").msgclass
  WebpageConditionOperandEnum::WebpageConditionOperand = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v4.enums.WebpageConditionOperandEnum.WebpageConditionOperand").enummodule
end
