# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v24/enums/local_services_lead_credit_issuance_decision.proto

require 'google/protobuf'


descriptor_data = "\nQgoogle/ads/googleads/v24/enums/local_services_lead_credit_issuance_decision.proto\x12\x1egoogle.ads.googleads.v24.enums\"\xd8\x01\n+LocalServicesLeadCreditIssuanceDecisionEnum\"\xa8\x01\n\x16\x43reditIssuanceDecision\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x0b\n\x07UNKNOWN\x10\x01\x12!\n\x1dSUCCESS_NOT_REACHED_THRESHOLD\x10\x02\x12\x1d\n\x19SUCCESS_REACHED_THRESHOLD\x10\x03\x12\x17\n\x13\x46\x41IL_OVER_THRESHOLD\x10\x04\x12\x15\n\x11\x46\x41IL_NOT_ELIGIBLE\x10\x05\x42\x86\x02\n\"com.google.ads.googleads.v24.enumsB,LocalServicesLeadCreditIssuanceDecisionProtoP\x01ZCgoogle.golang.org/genproto/googleapis/ads/googleads/v24/enums;enums\xa2\x02\x03GAA\xaa\x02\x1eGoogle.Ads.GoogleAds.V24.Enums\xca\x02\x1eGoogle\\Ads\\GoogleAds\\V24\\Enums\xea\x02\"Google::Ads::GoogleAds::V24::Enumsb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Google
  module Ads
    module GoogleAds
      module V24
        module Enums
          LocalServicesLeadCreditIssuanceDecisionEnum = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v24.enums.LocalServicesLeadCreditIssuanceDecisionEnum").msgclass
          LocalServicesLeadCreditIssuanceDecisionEnum::CreditIssuanceDecision = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v24.enums.LocalServicesLeadCreditIssuanceDecisionEnum.CreditIssuanceDecision").enummodule
        end
      end
    end
  end
end
