# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: google/ads/googleads/v23/services/incentive_service.proto for package 'Google.Ads.GoogleAds.V23.Services'
# Original file comments:
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

require 'grpc'
require 'google/ads/google_ads/v23/services/incentive_service_pb'

module Google
  module Ads
    module GoogleAds
      module V23
        module Services
          module IncentiveService
            # Service to support incentive related operations.
            class Service

              include ::GRPC::GenericService

              self.marshal_class_method = :encode
              self.unmarshal_class_method = :decode
              self.service_name = 'google.ads.googleads.v23.services.IncentiveService'

              # Returns incentives for a given user.
              rpc :FetchIncentive, ::Google::Ads::GoogleAds::V23::Services::FetchIncentiveRequest, ::Google::Ads::GoogleAds::V23::Services::FetchIncentiveResponse
              # Applies the incentive for the ads customer.
              rpc :ApplyIncentive, ::Google::Ads::GoogleAds::V23::Services::ApplyIncentiveRequest, ::Google::Ads::GoogleAds::V23::Services::ApplyIncentiveResponse
            end

            Stub = Service.rpc_stub_class
          end
        end
      end
    end
  end
end
