# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: google/ads/googleads/v23/services/youtube_video_upload_service.proto for package 'Google.Ads.GoogleAds.V23.Services'
# Original file comments:
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

require 'grpc'
require 'google/ads/google_ads/v23/services/youtube_video_upload_service_pb'

module Google
  module Ads
    module GoogleAds
      module V23
        module Services
          module YouTubeVideoUploadService
            # Proto file describing the YouTubeVideoUpload service.
            #
            # Service to manage YouTube video uploads.
            class Service

              include ::GRPC::GenericService

              self.marshal_class_method = :encode
              self.unmarshal_class_method = :decode
              self.service_name = 'google.ads.googleads.v23.services.YouTubeVideoUploadService'

              # Uploads a video to Google-managed or advertiser owned (brand) YouTube
              # channel.
              rpc :CreateYouTubeVideoUpload, ::Google::Ads::GoogleAds::V23::Services::CreateYouTubeVideoUploadRequest, ::Google::Ads::GoogleAds::V23::Services::CreateYouTubeVideoUploadResponse
              # Updates YouTube video's metadata, but only for videos uploaded using this
              # API.
              rpc :UpdateYouTubeVideoUpload, ::Google::Ads::GoogleAds::V23::Services::UpdateYouTubeVideoUploadRequest, ::Google::Ads::GoogleAds::V23::Services::UpdateYouTubeVideoUploadResponse
              # Removes YouTube videos uploaded using this API.
              rpc :RemoveYouTubeVideoUpload, ::Google::Ads::GoogleAds::V23::Services::RemoveYouTubeVideoUploadRequest, ::Google::Ads::GoogleAds::V23::Services::RemoveYouTubeVideoUploadResponse
            end

            Stub = Service.rpc_stub_class
          end
        end
      end
    end
  end
end
