# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v14/enums/feed_attribute_type.proto

require 'google/protobuf'


descriptor_data = "\n8google/ads/googleads/v14/enums/feed_attribute_type.proto\x12\x1egoogle.ads.googleads.v14.enums\"\x84\x02\n\x15\x46\x65\x65\x64\x41ttributeTypeEnum\"\xea\x01\n\x11\x46\x65\x65\x64\x41ttributeType\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x0b\n\x07UNKNOWN\x10\x01\x12\t\n\x05INT64\x10\x02\x12\n\n\x06\x44OUBLE\x10\x03\x12\n\n\x06STRING\x10\x04\x12\x0b\n\x07\x42OOLEAN\x10\x05\x12\x07\n\x03URL\x10\x06\x12\r\n\tDATE_TIME\x10\x07\x12\x0e\n\nINT64_LIST\x10\x08\x12\x0f\n\x0b\x44OUBLE_LIST\x10\t\x12\x0f\n\x0bSTRING_LIST\x10\n\x12\x10\n\x0c\x42OOLEAN_LIST\x10\x0b\x12\x0c\n\x08URL_LIST\x10\x0c\x12\x12\n\x0e\x44\x41TE_TIME_LIST\x10\r\x12\t\n\x05PRICE\x10\x0e\x42\xf0\x01\n\"com.google.ads.googleads.v14.enumsB\x16\x46\x65\x65\x64\x41ttributeTypeProtoP\x01ZCgoogle.golang.org/genproto/googleapis/ads/googleads/v14/enums;enums\xa2\x02\x03GAA\xaa\x02\x1eGoogle.Ads.GoogleAds.V14.Enums\xca\x02\x1eGoogle\\Ads\\GoogleAds\\V14\\Enums\xea\x02\"Google::Ads::GoogleAds::V14::Enumsb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError => e
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Google
  module Ads
    module GoogleAds
      module V14
        module Enums
          FeedAttributeTypeEnum = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v14.enums.FeedAttributeTypeEnum").msgclass
          FeedAttributeTypeEnum::FeedAttributeType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v14.enums.FeedAttributeTypeEnum.FeedAttributeType").enummodule
        end
      end
    end
  end
end
