# frozen_string_literal: true

# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!

# require "google/ads/google_ads/error"
require "google/ads/google_ads/v13/services/audience_insights_service_pb"

module Google
  module Ads
    module GoogleAds
      module V13
        module Services
          module AudienceInsightsService
            ##
            # Client for the AudienceInsightsService service.
            #
            # Audience Insights Service helps users find information about groups of
            # people and how they can be reached with Google Ads. Accessible to
            # allowlisted customers only.
            #
            class Client
              # @private
              attr_reader :audience_insights_service_stub

              ##
              # Configure the AudienceInsightsService Client class.
              #
              # See {::Google::Ads::GoogleAds::V13::Services::AudienceInsightsService::Client::Configuration}
              # for a description of the configuration fields.
              #
              # @example
              #
              #   # Modify the configuration for all AudienceInsightsService clients
              #   ::Google::Ads::GoogleAds::V13::Services::AudienceInsightsService::Client.configure do |config|
              #     config.timeout = 10.0
              #   end
              #
              # @yield [config] Configure the Client client.
              # @yieldparam config [Client::Configuration]
              #
              # @return [Client::Configuration]
              #
              def self.configure
                @configure ||= begin
                  default_config = Client::Configuration.new

                  default_config.timeout = 14_400.0
                  default_config.retry_policy = {
                    initial_delay: 5.0, max_delay: 60.0, multiplier: 1.3, retry_codes: [14, 4]
                  }

                  default_config
                end
                yield @configure if block_given?
                @configure
              end

              ##
              # Configure the AudienceInsightsService Client instance.
              #
              # The configuration is set to the derived mode, meaning that values can be changed,
              # but structural changes (adding new fields, etc.) are not allowed. Structural changes
              # should be made on {Client.configure}.
              #
              # See {::Google::Ads::GoogleAds::V13::Services::AudienceInsightsService::Client::Configuration}
              # for a description of the configuration fields.
              #
              # @yield [config] Configure the Client client.
              # @yieldparam config [Client::Configuration]
              #
              # @return [Client::Configuration]
              #
              def configure
                yield @config if block_given?
                @config
              end

              ##
              # Create a new AudienceInsightsService client object.
              #
              # @example
              #
              #   # Create a client using the default configuration
              #   client = ::Google::Ads::GoogleAds::V13::Services::AudienceInsightsService::Client.new
              #
              #   # Create a client using a custom configuration
              #   client = ::Google::Ads::GoogleAds::V13::Services::AudienceInsightsService::Client.new do |config|
              #     config.timeout = 10.0
              #   end
              #
              # @yield [config] Configure the AudienceInsightsService client.
              # @yieldparam config [Client::Configuration]
              #
              def initialize
                # These require statements are intentionally placed here to initialize
                # the gRPC module only when it's required.
                # See https://github.com/googleapis/toolkit/issues/446
                require "gapic/grpc"
                require "google/ads/google_ads/v13/services/audience_insights_service_services_pb"

                # Create the configuration object
                @config = Configuration.new Client.configure

                # Yield the configuration if needed
                yield @config if block_given?

                # Create credentials
                credentials = @config.credentials
                # Use self-signed JWT if the endpoint is unchanged from default,
                # but only if the default endpoint does not have a region prefix.
                enable_self_signed_jwt = @config.endpoint == Client.configure.endpoint &&
                                         !@config.endpoint.split(".").first.include?("-")
                credentials ||= Credentials.default scope: @config.scope,
                                                    enable_self_signed_jwt: enable_self_signed_jwt
                if credentials.is_a?(::String) || credentials.is_a?(::Hash)
                  credentials = Credentials.new credentials, scope: @config.scope
                end
                @quota_project_id = @config.quota_project
                @quota_project_id ||= credentials.quota_project_id if credentials.respond_to? :quota_project_id

                @audience_insights_service_stub = ::Gapic::ServiceStub.new(
                  ::Google::Ads::GoogleAds::V13::Services::AudienceInsightsService::Stub,
                  credentials:  credentials,
                  endpoint:     @config.endpoint,
                  channel_args: @config.channel_args,
                  interceptors: @config.interceptors
                )
              end

              # Service calls

              ##
              # Creates a saved report that can be viewed in the Insights Finder tool.
              #
              # List of thrown errors:
              #   [AuthenticationError]()
              #   [AuthorizationError]()
              #   [FieldError]()
              #   [HeaderError]()
              #   [InternalError]()
              #   [QuotaError]()
              #   [RangeError]()
              #   [RequestError]()
              #
              # @overload generate_insights_finder_report(request, options = nil)
              #   Pass arguments to `generate_insights_finder_report` via a request object, either of type
              #   {::Google::Ads::GoogleAds::V13::Services::GenerateInsightsFinderReportRequest} or an equivalent Hash.
              #
              #   @param request [::Google::Ads::GoogleAds::V13::Services::GenerateInsightsFinderReportRequest, ::Hash]
              #     A request object representing the call parameters. Required. To specify no
              #     parameters, or to keep all the default parameter values, pass an empty Hash.
              #   @param options [::Gapic::CallOptions, ::Hash]
              #     Overrides the default settings for this call, e.g, timeout, retries, etc. Optional.
              #
              # @overload generate_insights_finder_report(customer_id: nil, baseline_audience: nil, specific_audience: nil, customer_insights_group: nil)
              #   Pass arguments to `generate_insights_finder_report` via keyword arguments. Note that at
              #   least one keyword argument is required. To specify no parameters, or to keep all
              #   the default parameter values, pass an empty Hash as a request object (see above).
              #
              #   @param customer_id [::String]
              #     Required. The ID of the customer.
              #   @param baseline_audience [::Google::Ads::GoogleAds::V13::Services::BasicInsightsAudience, ::Hash]
              #     Required. A baseline audience for this report, typically all people in a
              #     region.
              #   @param specific_audience [::Google::Ads::GoogleAds::V13::Services::BasicInsightsAudience, ::Hash]
              #     Required. The specific audience of interest for this report.  The insights
              #     in the report will be based on attributes more prevalent in this audience
              #     than in the report's baseline audience.
              #   @param customer_insights_group [::String]
              #     The name of the customer being planned for.  This is a user-defined value.
              #
              # @yield [response, operation] Access the result along with the RPC operation
              # @yieldparam response [::Google::Ads::GoogleAds::V13::Services::GenerateInsightsFinderReportResponse]
              # @yieldparam operation [::GRPC::ActiveCall::Operation]
              #
              # @return [::Google::Ads::GoogleAds::V13::Services::GenerateInsightsFinderReportResponse]
              #
              # @raise [Google::Ads::GoogleAds::Error] if the RPC is aborted.
              #
              # @example Basic example
              #   require "google/ads/google_ads/v13/services"
              #
              #   # Create a client object. The client can be reused for multiple calls.
              #   client = Google::Ads::GoogleAds::V13::Services::AudienceInsightsService::Client.new
              #
              #   # Create a request. To set request fields, pass in keyword arguments.
              #   request = Google::Ads::GoogleAds::V13::Services::GenerateInsightsFinderReportRequest.new
              #
              #   # Call the generate_insights_finder_report method.
              #   result = client.generate_insights_finder_report request
              #
              #   # The returned object is of type Google::Ads::GoogleAds::V13::Services::GenerateInsightsFinderReportResponse.
              #   p result
              #
              def generate_insights_finder_report request, options = nil
                raise ::ArgumentError, "request must be provided" if request.nil?

                request = ::Gapic::Protobuf.coerce request,
                                                   to: ::Google::Ads::GoogleAds::V13::Services::GenerateInsightsFinderReportRequest

                # Converts hash and nil to an options object
                options = ::Gapic::CallOptions.new(**options.to_h) if options.respond_to? :to_h

                # Customize the options with defaults
                metadata = @config.rpcs.generate_insights_finder_report.metadata.to_h

                # Set x-goog-api-client and x-goog-user-project headers
                metadata[:"x-goog-api-client"] ||= ::Gapic::Headers.x_goog_api_client \
                  lib_name: @config.lib_name, lib_version: @config.lib_version,
                  gapic_version: ::Google::Ads::GoogleAds::VERSION
                metadata[:"x-goog-user-project"] = @quota_project_id if @quota_project_id

                header_params = {}
                if request.customer_id
                  header_params["customer_id"] = request.customer_id
                end

                request_params_header = header_params.map { |k, v| "#{k}=#{v}" }.join("&")
                metadata[:"x-goog-request-params"] ||= request_params_header

                options.apply_defaults timeout:      @config.rpcs.generate_insights_finder_report.timeout,
                                       metadata:     metadata,
                                       retry_policy: @config.rpcs.generate_insights_finder_report.retry_policy

                options.apply_defaults timeout:      @config.timeout,
                                       metadata:     @config.metadata,
                                       retry_policy: @config.retry_policy

                @audience_insights_service_stub.call_rpc :generate_insights_finder_report, request,
                                                         options: options do |response, operation|
                  yield response, operation if block_given?
                  return response
                end
                # rescue GRPC::BadStatus => grpc_error
                #  raise Google::Ads::GoogleAds::Error.new grpc_error.message
              end

              ##
              # Searches for audience attributes that can be used to generate insights.
              #
              # List of thrown errors:
              #   [AuthenticationError]()
              #   [AuthorizationError]()
              #   [FieldError]()
              #   [HeaderError]()
              #   [InternalError]()
              #   [QuotaError]()
              #   [RangeError]()
              #   [RequestError]()
              #
              # @overload list_audience_insights_attributes(request, options = nil)
              #   Pass arguments to `list_audience_insights_attributes` via a request object, either of type
              #   {::Google::Ads::GoogleAds::V13::Services::ListAudienceInsightsAttributesRequest} or an equivalent Hash.
              #
              #   @param request [::Google::Ads::GoogleAds::V13::Services::ListAudienceInsightsAttributesRequest, ::Hash]
              #     A request object representing the call parameters. Required. To specify no
              #     parameters, or to keep all the default parameter values, pass an empty Hash.
              #   @param options [::Gapic::CallOptions, ::Hash]
              #     Overrides the default settings for this call, e.g, timeout, retries, etc. Optional.
              #
              # @overload list_audience_insights_attributes(customer_id: nil, dimensions: nil, query_text: nil, customer_insights_group: nil, location_country_filters: nil)
              #   Pass arguments to `list_audience_insights_attributes` via keyword arguments. Note that at
              #   least one keyword argument is required. To specify no parameters, or to keep all
              #   the default parameter values, pass an empty Hash as a request object (see above).
              #
              #   @param customer_id [::String]
              #     Required. The ID of the customer.
              #   @param dimensions [::Array<::Google::Ads::GoogleAds::V13::Enums::AudienceInsightsDimensionEnum::AudienceInsightsDimension>]
              #     Required. The types of attributes to be returned.
              #   @param query_text [::String]
              #     Required. A free text query.  Attributes matching or related to this string
              #     will be returned.
              #   @param customer_insights_group [::String]
              #     The name of the customer being planned for.  This is a user-defined value.
              #   @param location_country_filters [::Array<::Google::Ads::GoogleAds::V13::Common::LocationInfo, ::Hash>]
              #     If SUB_COUNTRY_LOCATION attributes are one of the requested dimensions and
              #     this field is present, then the SUB_COUNTRY_LOCATION attributes returned
              #     will be located in these countries. If this field is absent, then location
              #     attributes are not filtered by country. Setting this field when
              #     SUB_COUNTRY_LOCATION attributes are not requested will return an error.
              #
              # @yield [response, operation] Access the result along with the RPC operation
              # @yieldparam response [::Google::Ads::GoogleAds::V13::Services::ListAudienceInsightsAttributesResponse]
              # @yieldparam operation [::GRPC::ActiveCall::Operation]
              #
              # @return [::Google::Ads::GoogleAds::V13::Services::ListAudienceInsightsAttributesResponse]
              #
              # @raise [Google::Ads::GoogleAds::Error] if the RPC is aborted.
              #
              # @example Basic example
              #   require "google/ads/google_ads/v13/services"
              #
              #   # Create a client object. The client can be reused for multiple calls.
              #   client = Google::Ads::GoogleAds::V13::Services::AudienceInsightsService::Client.new
              #
              #   # Create a request. To set request fields, pass in keyword arguments.
              #   request = Google::Ads::GoogleAds::V13::Services::ListAudienceInsightsAttributesRequest.new
              #
              #   # Call the list_audience_insights_attributes method.
              #   result = client.list_audience_insights_attributes request
              #
              #   # The returned object is of type Google::Ads::GoogleAds::V13::Services::ListAudienceInsightsAttributesResponse.
              #   p result
              #
              def list_audience_insights_attributes request, options = nil
                raise ::ArgumentError, "request must be provided" if request.nil?

                request = ::Gapic::Protobuf.coerce request,
                                                   to: ::Google::Ads::GoogleAds::V13::Services::ListAudienceInsightsAttributesRequest

                # Converts hash and nil to an options object
                options = ::Gapic::CallOptions.new(**options.to_h) if options.respond_to? :to_h

                # Customize the options with defaults
                metadata = @config.rpcs.list_audience_insights_attributes.metadata.to_h

                # Set x-goog-api-client and x-goog-user-project headers
                metadata[:"x-goog-api-client"] ||= ::Gapic::Headers.x_goog_api_client \
                  lib_name: @config.lib_name, lib_version: @config.lib_version,
                  gapic_version: ::Google::Ads::GoogleAds::VERSION
                metadata[:"x-goog-user-project"] = @quota_project_id if @quota_project_id

                header_params = {}
                if request.customer_id
                  header_params["customer_id"] = request.customer_id
                end

                request_params_header = header_params.map { |k, v| "#{k}=#{v}" }.join("&")
                metadata[:"x-goog-request-params"] ||= request_params_header

                options.apply_defaults timeout:      @config.rpcs.list_audience_insights_attributes.timeout,
                                       metadata:     metadata,
                                       retry_policy: @config.rpcs.list_audience_insights_attributes.retry_policy

                options.apply_defaults timeout:      @config.timeout,
                                       metadata:     @config.metadata,
                                       retry_policy: @config.retry_policy

                @audience_insights_service_stub.call_rpc :list_audience_insights_attributes, request,
                                                         options: options do |response, operation|
                  yield response, operation if block_given?
                  return response
                end
                # rescue GRPC::BadStatus => grpc_error
                #  raise Google::Ads::GoogleAds::Error.new grpc_error.message
              end

              ##
              # Lists date ranges for which audience insights data can be requested.
              #
              # List of thrown errors:
              #   [AuthenticationError]()
              #   [AuthorizationError]()
              #   [FieldError]()
              #   [HeaderError]()
              #   [InternalError]()
              #   [QuotaError]()
              #   [RangeError]()
              #   [RequestError]()
              #
              # @overload list_insights_eligible_dates(request, options = nil)
              #   Pass arguments to `list_insights_eligible_dates` via a request object, either of type
              #   {::Google::Ads::GoogleAds::V13::Services::ListInsightsEligibleDatesRequest} or an equivalent Hash.
              #
              #   @param request [::Google::Ads::GoogleAds::V13::Services::ListInsightsEligibleDatesRequest, ::Hash]
              #     A request object representing the call parameters. Required. To specify no
              #     parameters, or to keep all the default parameter values, pass an empty Hash.
              #   @param options [::Gapic::CallOptions, ::Hash]
              #     Overrides the default settings for this call, e.g, timeout, retries, etc. Optional.
              #
              # @yield [response, operation] Access the result along with the RPC operation
              # @yieldparam response [::Google::Ads::GoogleAds::V13::Services::ListInsightsEligibleDatesResponse]
              # @yieldparam operation [::GRPC::ActiveCall::Operation]
              #
              # @return [::Google::Ads::GoogleAds::V13::Services::ListInsightsEligibleDatesResponse]
              #
              # @raise [Google::Ads::GoogleAds::Error] if the RPC is aborted.
              #
              # @example Basic example
              #   require "google/ads/google_ads/v13/services"
              #
              #   # Create a client object. The client can be reused for multiple calls.
              #   client = Google::Ads::GoogleAds::V13::Services::AudienceInsightsService::Client.new
              #
              #   # Create a request. To set request fields, pass in keyword arguments.
              #   request = Google::Ads::GoogleAds::V13::Services::ListInsightsEligibleDatesRequest.new
              #
              #   # Call the list_insights_eligible_dates method.
              #   result = client.list_insights_eligible_dates request
              #
              #   # The returned object is of type Google::Ads::GoogleAds::V13::Services::ListInsightsEligibleDatesResponse.
              #   p result
              #
              def list_insights_eligible_dates request, options = nil
                raise ::ArgumentError, "request must be provided" if request.nil?

                request = ::Gapic::Protobuf.coerce request,
                                                   to: ::Google::Ads::GoogleAds::V13::Services::ListInsightsEligibleDatesRequest

                # Converts hash and nil to an options object
                options = ::Gapic::CallOptions.new(**options.to_h) if options.respond_to? :to_h

                # Customize the options with defaults
                metadata = @config.rpcs.list_insights_eligible_dates.metadata.to_h

                # Set x-goog-api-client and x-goog-user-project headers
                metadata[:"x-goog-api-client"] ||= ::Gapic::Headers.x_goog_api_client \
                  lib_name: @config.lib_name, lib_version: @config.lib_version,
                  gapic_version: ::Google::Ads::GoogleAds::VERSION
                metadata[:"x-goog-user-project"] = @quota_project_id if @quota_project_id

                options.apply_defaults timeout:      @config.rpcs.list_insights_eligible_dates.timeout,
                                       metadata:     metadata,
                                       retry_policy: @config.rpcs.list_insights_eligible_dates.retry_policy

                options.apply_defaults timeout:      @config.timeout,
                                       metadata:     @config.metadata,
                                       retry_policy: @config.retry_policy

                @audience_insights_service_stub.call_rpc :list_insights_eligible_dates, request,
                                                         options: options do |response, operation|
                  yield response, operation if block_given?
                  return response
                end
                # rescue GRPC::BadStatus => grpc_error
                #  raise Google::Ads::GoogleAds::Error.new grpc_error.message
              end

              ##
              # Returns a collection of attributes that are represented in an audience of
              # interest, with metrics that compare each attribute's share of the audience
              # with its share of a baseline audience.
              #
              # List of thrown errors:
              #   [AudienceInsightsError]()
              #   [AuthenticationError]()
              #   [AuthorizationError]()
              #   [FieldError]()
              #   [HeaderError]()
              #   [InternalError]()
              #   [QuotaError]()
              #   [RangeError]()
              #   [RequestError]()
              #
              # @overload generate_audience_composition_insights(request, options = nil)
              #   Pass arguments to `generate_audience_composition_insights` via a request object, either of type
              #   {::Google::Ads::GoogleAds::V13::Services::GenerateAudienceCompositionInsightsRequest} or an equivalent Hash.
              #
              #   @param request [::Google::Ads::GoogleAds::V13::Services::GenerateAudienceCompositionInsightsRequest, ::Hash]
              #     A request object representing the call parameters. Required. To specify no
              #     parameters, or to keep all the default parameter values, pass an empty Hash.
              #   @param options [::Gapic::CallOptions, ::Hash]
              #     Overrides the default settings for this call, e.g, timeout, retries, etc. Optional.
              #
              # @overload generate_audience_composition_insights(customer_id: nil, audience: nil, baseline_audience: nil, data_month: nil, dimensions: nil, customer_insights_group: nil)
              #   Pass arguments to `generate_audience_composition_insights` via keyword arguments. Note that at
              #   least one keyword argument is required. To specify no parameters, or to keep all
              #   the default parameter values, pass an empty Hash as a request object (see above).
              #
              #   @param customer_id [::String]
              #     Required. The ID of the customer.
              #   @param audience [::Google::Ads::GoogleAds::V13::Services::InsightsAudience, ::Hash]
              #     Required. The audience of interest for which insights are being requested.
              #   @param baseline_audience [::Google::Ads::GoogleAds::V13::Services::InsightsAudience, ::Hash]
              #     The baseline audience to which the audience of interest is being
              #     compared.
              #   @param data_month [::String]
              #     The one-month range of historical data to use for insights, in the format
              #     "yyyy-mm". If unset, insights will be returned for the last thirty days of
              #     data.
              #   @param dimensions [::Array<::Google::Ads::GoogleAds::V13::Enums::AudienceInsightsDimensionEnum::AudienceInsightsDimension>]
              #     Required. The audience dimensions for which composition insights should be
              #     returned.
              #   @param customer_insights_group [::String]
              #     The name of the customer being planned for.  This is a user-defined value.
              #
              # @yield [response, operation] Access the result along with the RPC operation
              # @yieldparam response [::Google::Ads::GoogleAds::V13::Services::GenerateAudienceCompositionInsightsResponse]
              # @yieldparam operation [::GRPC::ActiveCall::Operation]
              #
              # @return [::Google::Ads::GoogleAds::V13::Services::GenerateAudienceCompositionInsightsResponse]
              #
              # @raise [Google::Ads::GoogleAds::Error] if the RPC is aborted.
              #
              # @example Basic example
              #   require "google/ads/google_ads/v13/services"
              #
              #   # Create a client object. The client can be reused for multiple calls.
              #   client = Google::Ads::GoogleAds::V13::Services::AudienceInsightsService::Client.new
              #
              #   # Create a request. To set request fields, pass in keyword arguments.
              #   request = Google::Ads::GoogleAds::V13::Services::GenerateAudienceCompositionInsightsRequest.new
              #
              #   # Call the generate_audience_composition_insights method.
              #   result = client.generate_audience_composition_insights request
              #
              #   # The returned object is of type Google::Ads::GoogleAds::V13::Services::GenerateAudienceCompositionInsightsResponse.
              #   p result
              #
              def generate_audience_composition_insights request, options = nil
                raise ::ArgumentError, "request must be provided" if request.nil?

                request = ::Gapic::Protobuf.coerce request,
                                                   to: ::Google::Ads::GoogleAds::V13::Services::GenerateAudienceCompositionInsightsRequest

                # Converts hash and nil to an options object
                options = ::Gapic::CallOptions.new(**options.to_h) if options.respond_to? :to_h

                # Customize the options with defaults
                metadata = @config.rpcs.generate_audience_composition_insights.metadata.to_h

                # Set x-goog-api-client and x-goog-user-project headers
                metadata[:"x-goog-api-client"] ||= ::Gapic::Headers.x_goog_api_client \
                  lib_name: @config.lib_name, lib_version: @config.lib_version,
                  gapic_version: ::Google::Ads::GoogleAds::VERSION
                metadata[:"x-goog-user-project"] = @quota_project_id if @quota_project_id

                header_params = {}
                if request.customer_id
                  header_params["customer_id"] = request.customer_id
                end

                request_params_header = header_params.map { |k, v| "#{k}=#{v}" }.join("&")
                metadata[:"x-goog-request-params"] ||= request_params_header

                options.apply_defaults timeout:      @config.rpcs.generate_audience_composition_insights.timeout,
                                       metadata:     metadata,
                                       retry_policy: @config.rpcs.generate_audience_composition_insights.retry_policy

                options.apply_defaults timeout:      @config.timeout,
                                       metadata:     @config.metadata,
                                       retry_policy: @config.retry_policy

                @audience_insights_service_stub.call_rpc :generate_audience_composition_insights, request,
                                                         options: options do |response, operation|
                  yield response, operation if block_given?
                  return response
                end
                # rescue GRPC::BadStatus => grpc_error
                #  raise Google::Ads::GoogleAds::Error.new grpc_error.message
              end

              ##
              # Configuration class for the AudienceInsightsService API.
              #
              # This class represents the configuration for AudienceInsightsService,
              # providing control over timeouts, retry behavior, logging, transport
              # parameters, and other low-level controls. Certain parameters can also be
              # applied individually to specific RPCs. See
              # {::Google::Ads::GoogleAds::V13::Services::AudienceInsightsService::Client::Configuration::Rpcs}
              # for a list of RPCs that can be configured independently.
              #
              # Configuration can be applied globally to all clients, or to a single client
              # on construction.
              #
              # @example
              #
              #   # Modify the global config, setting the timeout for
              #   # generate_insights_finder_report to 20 seconds,
              #   # and all remaining timeouts to 10 seconds.
              #   ::Google::Ads::GoogleAds::V13::Services::AudienceInsightsService::Client.configure do |config|
              #     config.timeout = 10.0
              #     config.rpcs.generate_insights_finder_report.timeout = 20.0
              #   end
              #
              #   # Apply the above configuration only to a new client.
              #   client = ::Google::Ads::GoogleAds::V13::Services::AudienceInsightsService::Client.new do |config|
              #     config.timeout = 10.0
              #     config.rpcs.generate_insights_finder_report.timeout = 20.0
              #   end
              #
              # @!attribute [rw] endpoint
              #   The hostname or hostname:port of the service endpoint.
              #   Defaults to `"googleads.googleapis.com"`.
              #   @return [::String]
              # @!attribute [rw] credentials
              #   Credentials to send with calls. You may provide any of the following types:
              #    *  (`String`) The path to a service account key file in JSON format
              #    *  (`Hash`) A service account key as a Hash
              #    *  (`Google::Auth::Credentials`) A googleauth credentials object
              #       (see the [googleauth docs](https://rubydoc.info/gems/googleauth/Google/Auth/Credentials))
              #    *  (`Signet::OAuth2::Client`) A signet oauth2 client object
              #       (see the [signet docs](https://rubydoc.info/gems/signet/Signet/OAuth2/Client))
              #    *  (`GRPC::Core::Channel`) a gRPC channel with included credentials
              #    *  (`GRPC::Core::ChannelCredentials`) a gRPC credentails object
              #    *  (`nil`) indicating no credentials
              #   @return [::Object]
              # @!attribute [rw] scope
              #   The OAuth scopes
              #   @return [::Array<::String>]
              # @!attribute [rw] lib_name
              #   The library name as recorded in instrumentation and logging
              #   @return [::String]
              # @!attribute [rw] lib_version
              #   The library version as recorded in instrumentation and logging
              #   @return [::String]
              # @!attribute [rw] channel_args
              #   Extra parameters passed to the gRPC channel. Note: this is ignored if a
              #   `GRPC::Core::Channel` object is provided as the credential.
              #   @return [::Hash]
              # @!attribute [rw] interceptors
              #   An array of interceptors that are run before calls are executed.
              #   @return [::Array<::GRPC::ClientInterceptor>]
              # @!attribute [rw] timeout
              #   The call timeout in seconds.
              #   @return [::Numeric]
              # @!attribute [rw] metadata
              #   Additional gRPC headers to be sent with the call.
              #   @return [::Hash{::Symbol=>::String}]
              # @!attribute [rw] retry_policy
              #   The retry policy. The value is a hash with the following keys:
              #    *  `:initial_delay` (*type:* `Numeric`) - The initial delay in seconds.
              #    *  `:max_delay` (*type:* `Numeric`) - The max delay in seconds.
              #    *  `:multiplier` (*type:* `Numeric`) - The incremental backoff multiplier.
              #    *  `:retry_codes` (*type:* `Array<String>`) - The error codes that should
              #       trigger a retry.
              #   @return [::Hash]
              # @!attribute [rw] quota_project
              #   A separate project against which to charge quota.
              #   @return [::String]
              #
              class Configuration
                extend ::Gapic::Config

                config_attr :endpoint,      "googleads.googleapis.com", ::String
                config_attr :credentials,   nil do |value|
                  allowed = [::String, ::Hash, ::Proc, ::Symbol, ::Google::Auth::Credentials, ::Signet::OAuth2::Client,
                             nil]
                  allowed += [::GRPC::Core::Channel, ::GRPC::Core::ChannelCredentials] if defined? ::GRPC
                  allowed.any? { |klass| klass === value }
                end
                config_attr :scope,         nil, ::String, ::Array, nil
                config_attr :lib_name,      nil, ::String, nil
                config_attr :lib_version,   nil, ::String, nil
                config_attr(:channel_args,  { "grpc.service_config_disable_resolution" => 1 }, ::Hash, nil)
                config_attr :interceptors,  nil, ::Array, nil
                config_attr :timeout,       nil, ::Numeric, nil
                config_attr :metadata,      nil, ::Hash, nil
                config_attr :retry_policy,  nil, ::Hash, ::Proc, nil
                config_attr :quota_project, nil, ::String, nil

                # @private
                def initialize parent_config = nil
                  @parent_config = parent_config unless parent_config.nil?

                  yield self if block_given?
                end

                ##
                # Configurations for individual RPCs
                # @return [Rpcs]
                #
                def rpcs
                  @rpcs ||= begin
                    parent_rpcs = nil
                    parent_rpcs = @parent_config.rpcs if defined?(@parent_config) && @parent_config.respond_to?(:rpcs)
                    Rpcs.new parent_rpcs
                  end
                end

                ##
                # Configuration RPC class for the AudienceInsightsService API.
                #
                # Includes fields providing the configuration for each RPC in this service.
                # Each configuration object is of type `Gapic::Config::Method` and includes
                # the following configuration fields:
                #
                #  *  `timeout` (*type:* `Numeric`) - The call timeout in seconds
                #  *  `metadata` (*type:* `Hash{Symbol=>String}`) - Additional gRPC headers
                #  *  `retry_policy (*type:* `Hash`) - The retry policy. The policy fields
                #     include the following keys:
                #      *  `:initial_delay` (*type:* `Numeric`) - The initial delay in seconds.
                #      *  `:max_delay` (*type:* `Numeric`) - The max delay in seconds.
                #      *  `:multiplier` (*type:* `Numeric`) - The incremental backoff multiplier.
                #      *  `:retry_codes` (*type:* `Array<String>`) - The error codes that should
                #         trigger a retry.
                #
                class Rpcs
                  ##
                  # RPC-specific configuration for `generate_insights_finder_report`
                  # @return [::Gapic::Config::Method]
                  #
                  attr_reader :generate_insights_finder_report
                  ##
                  # RPC-specific configuration for `list_audience_insights_attributes`
                  # @return [::Gapic::Config::Method]
                  #
                  attr_reader :list_audience_insights_attributes
                  ##
                  # RPC-specific configuration for `list_insights_eligible_dates`
                  # @return [::Gapic::Config::Method]
                  #
                  attr_reader :list_insights_eligible_dates
                  ##
                  # RPC-specific configuration for `generate_audience_composition_insights`
                  # @return [::Gapic::Config::Method]
                  #
                  attr_reader :generate_audience_composition_insights

                  # @private
                  def initialize parent_rpcs = nil
                    generate_insights_finder_report_config = parent_rpcs.generate_insights_finder_report if parent_rpcs.respond_to? :generate_insights_finder_report
                    @generate_insights_finder_report = ::Gapic::Config::Method.new generate_insights_finder_report_config
                    list_audience_insights_attributes_config = parent_rpcs.list_audience_insights_attributes if parent_rpcs.respond_to? :list_audience_insights_attributes
                    @list_audience_insights_attributes = ::Gapic::Config::Method.new list_audience_insights_attributes_config
                    list_insights_eligible_dates_config = parent_rpcs.list_insights_eligible_dates if parent_rpcs.respond_to? :list_insights_eligible_dates
                    @list_insights_eligible_dates = ::Gapic::Config::Method.new list_insights_eligible_dates_config
                    generate_audience_composition_insights_config = parent_rpcs.generate_audience_composition_insights if parent_rpcs.respond_to? :generate_audience_composition_insights
                    @generate_audience_composition_insights = ::Gapic::Config::Method.new generate_audience_composition_insights_config

                    yield self if block_given?
                  end
                end
              end
            end
          end
        end
      end
    end
  end
end
