# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v24/errors/ad_group_bid_modifier_error.proto

require 'google/protobuf'


descriptor_data = "\nAgoogle/ads/googleads/v24/errors/ad_group_bid_modifier_error.proto\x12\x1fgoogle.ads.googleads.v24.errors\"\xb6\x01\n\x1b\x41\x64GroupBidModifierErrorEnum\"\x96\x01\n\x17\x41\x64GroupBidModifierError\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x0b\n\x07UNKNOWN\x10\x01\x12\x1e\n\x1a\x43RITERION_ID_NOT_SUPPORTED\x10\x02\x12=\n9CANNOT_OVERRIDE_OPTED_OUT_CAMPAIGN_CRITERION_BID_MODIFIER\x10\x03\x42\xfc\x01\n#com.google.ads.googleads.v24.errorsB\x1c\x41\x64GroupBidModifierErrorProtoP\x01ZEgoogle.golang.org/genproto/googleapis/ads/googleads/v24/errors;errors\xa2\x02\x03GAA\xaa\x02\x1fGoogle.Ads.GoogleAds.V24.Errors\xca\x02\x1fGoogle\\Ads\\GoogleAds\\V24\\Errors\xea\x02#Google::Ads::GoogleAds::V24::Errorsb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Google
  module Ads
    module GoogleAds
      module V24
        module Errors
          AdGroupBidModifierErrorEnum = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v24.errors.AdGroupBidModifierErrorEnum").msgclass
          AdGroupBidModifierErrorEnum::AdGroupBidModifierError = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v24.errors.AdGroupBidModifierErrorEnum.AdGroupBidModifierError").enummodule
        end
      end
    end
  end
end
