# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/google_ads/v1/enums/budget_delivery_method.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "google.ads.googleads.v1.enums.BudgetDeliveryMethodEnum" do
  end
  add_enum "google.ads.googleads.v1.enums.BudgetDeliveryMethodEnum.BudgetDeliveryMethod" do
    value :UNSPECIFIED, 0
    value :UNKNOWN, 1
    value :STANDARD, 2
    value :ACCELERATED, 3
  end
end

module Google::Ads::GoogleAds::V1::Enums
  BudgetDeliveryMethodEnum = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v1.enums.BudgetDeliveryMethodEnum").msgclass
  BudgetDeliveryMethodEnum::BudgetDeliveryMethod = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v1.enums.BudgetDeliveryMethodEnum.BudgetDeliveryMethod").enummodule
end
